### ISSUE TITLE
translate sensor status

### ISSUE THREAD

**Issue by thetux07** [vincentwolsink/home_assistant_micronova_agua_iot#103]
hello
thank you for you job
how to translate text of status sensor
thank you

**Comment by vincentwolsink** [comment]
You should use a [template](https://www.home-assistant.io/integrations/template/) sensor. An example can be found [here](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/issues/49#issuecomment-1774024303). But be aware that the example might not be applicable to your stove (status numbers might differ).

**Comment by thetux07** [comment]
Good morning,
the solution is good, thank you very much, I was going on the principle of translating directly in the custum_component but actually it works very well like that thank you
