### ISSUE TITLE
Change unit of climate entity

### ISSUE THREAD

**Issue by rvannunen** [vincentwolsink/home_assistant_micronova_agua_iot#107]
Hello,

Probably not an issue, but more a question. I installed the integration, configured my Nobis Round Up stove without any problem. I now see 1 device and 6 entities, including 1 climate entity and 2 sensors temperature (smoke temperature and flame temperature). These 3 entities were by default in Fahrenheit. I managed to change smoke and flame temperature to Celsius (via developper tool > states). But I do not find the way to transform the climate entity to Celsius.

Can you please indicate me how to change it? My other temperatures in Home Assistant are all in Celsius, I do not understand why this integration used Fahrenheit by default.

Thanks for your help, and a huge thank for your work, this integration et your reactivity.

**Comment by jipem01** [comment]
I confirm that's an issue. Dunno if it's the stove or integrations.But it's the first time that we heard about depsite having some user feedbacks with nobis stoves ( unica A10V from my side...)Could you share integration diagnosis?

**Comment by rvannunen** [comment]
Thanks for you quick anwser. I checked again this morning, and saw that the unit system of my Home Assistant (Settings > System > General) had switched to Fahrenheit for a reason I don't understand. I modified it back to Celsius, reloaded my stove in the integration and everything is now expressed in Celsius.

Sorry for the disturbance.
