### ISSUE TITLE
no pellet in dashboard only wood - unica nobis fire

### ISSUE THREAD

**Issue by merlino1975** [vincentwolsink/home_assistant_micronova_agua_iot#108]
![20231124_124814](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/34696169/7b6d57ab-ca3d-4c2e-b483-b546da35b085)
I apologize.. perhaps I expressed myself badly in the previous message.
Today I turned it on remotely (obviously in pellet mode) but in the dashboard I always see wood as the setting, shouldn't I see pellets? Am I doing something wrong or is it stuck?
I have already tried restarting Home Assistant.
thank you so much

well, not so if I explained myself.
In the image I should see pellets and no wood, but instead I always see wood (at the moment pellets are burning)

**Comment by vincentwolsink** [comment]
Please send a diagnostics file from when the stove is burning pellets.

**Comment by merlino1975** [comment]
forgive my ignorance.. where do I find the file you want me to send you?

Now it s burning pellets

**Comment by vincentwolsink** [comment]
Go to the integration in settings. Click your device and then on download diagnostics.

[![Open your Home Assistant instance and show an integration.](https://my.home-assistant.io/badges/integration.svg)](https://my.home-assistant.io/redirect/integration/?domain=aguaiot)

**Comment by merlino1975** [comment]
[config_entry-aguaiot-a475d1b727a4297411d5fb74935c487a.json.txt.json](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/files/13462060/config_entry-aguaiot-a475d1b727a4297411d5fb74935c487a.json.txt.json)

**Comment by vincentwolsink** [comment]
@jipem01 Is the switching of the climate entity between modes functioning correctly for your stove? I am currently checking on `power_wood_enable` but now it seems I should check on `real_power_wood_enable`.

**Comment by merlino1975** [comment]
..i dont  undestand..it s a my setting or other?

**Comment by vincentwolsink** [comment]
Download the newest version (0.3.0), should be fixed there.

**Comment by jipem01** [comment]
I confirm the bug.
I've created a templated sensor to watch mode and it stay all the time to wood (i've just checked history)
Didn't notice before as I use mainly wood.

**Comment by merlino1975** [comment]
Another questione...my remote control has sensor temeperature...i whact it and is 99 grades temperature..it is a problem of remote control or may be a problem of compatibility agua iot?

**Comment by jipem01** [comment]
@vincentwolsink  i confirmed, solved with 0.3.0.
@merlino1975 if the remote display 99 you should check with your stove resseller. HA and micronova plugin should have no impact on it.

**Comment by merlino1975** [comment]
yes...I just do it...I called my dealer....but...I don't know...everyone says what is useful to them...well...now...it's so complicated . ..I try to use the wood mode..but often when the wood runs out the "wood is running out" alarm doesn't sound and the pellets start burning again...
I think I have a problem with the stove.... I hope to resolve it under warranty... but it's hard
I tried turning off home assistant (obviously also agua iot) to check if there was a possibility that some interactions could create conflicts. But it seems to behave the same way
