### ISSUE TITLE
Feature request: powerful and auto mode for Nobis stove

### ISSUE THREAD

**Issue by rvannunen** [vincentwolsink/home_assistant_micronova_agua_iot#111]
Hello,

This is a feature request, not a bug. I have a Nobis Round stove. Integration is working perfectly. In the Nobis application, I am able, in the Settings tab, to view and set two parameters:
- Auto mode, which adapt automatically the fan speed with the power level
- Powerful mode

In the Home Assistant integration, I didn’t find the equivalent settings/sensor/switch. Would it be possible to add the ability to see the value of these parameters, and ideally to change them?

Please find attached the diagnostic file and the screenshot of the app. There seems to be a fun_auto_set and a fun_pwf_set section which seems related to my request.

Thanks in advance,

Raphaël
![IMG_3044](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/146890510/97dfb1e0-3da2-4e36-b5cb-9fc2b6ad8ed6)
![IMG_3045](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/146890510/2ec847be-6764-4136-9100-2a86e74dc5cf)
[config_entry-aguaiot-b07f7f1c781489ec48359305df0a7988.json.txt.json](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/files/13551478/config_entry-aguaiot-b07f7f1c781489ec48359305df0a7988.json.txt.json)

**Comment by vincentwolsink** [comment]
Implemented in [v0.3.1](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/releases/tag/v0.3.1) :)
