### ISSUE TITLE
Cadel Cristal usage in HA?

### ISSUE THREAD

**Issue by JarlBeN** [vincentwolsink/home_assistant_micronova_agua_iot#113]
Hello and thank you for your work. I managed to add it to Home Assistant. But I'm a bit lost, how do I get HA to see my stove (a Cadel Cristal)?

**Comment by vincentwolsink** [comment]
Hi @JarlBeN, which app on your phone do you use to connect to the stove? I need to see if your stove is compatible with this integration.

**Comment by JarlBeN** [comment]
What reactivity !
I use: Easy Connect Plus with my Cadel Cristal.

**Comment by vincentwolsink** [comment]
Did you try to add the integration and enter the customer code + url for Easy Connect Plus from the table in the readme?

**Comment by JarlBeN** [comment]
I have the code "746318" but I don't know where to add it for the integration... sorry

**Comment by vincentwolsink** [comment]
[![Open your Home Assistant instance and start setting up a new integration.](https://my.home-assistant.io/badges/config_flow_start.svg)](https://my.home-assistant.io/redirect/config_flow_start/?domain=aguaiot)

**Comment by JarlBeN** [comment]
Great, it works, and it works very well! I hadn't managed to get this settings window. A big thank you! I am surprised by the need to enter "easy connect plus" credentials. I wanted to know if the commands sent to the stove remain local or go through their servers?

**Comment by vincentwolsink** [comment]
All communication goes through their servers. Unfortunately it is currently not possible to control the stove locally without additional custom hardware.

**Comment by JarlBeN** [comment]
Okay, thank you. I thought there might be something to do with Bluetooth. Thanks again for the work and for the help!
