### ISSUE TITLE
Feature request: Fan speed control for Nobis stove

### ISSUE THREAD

**Issue by rvannunen** [vincentwolsink/home_assistant_micronova_agua_iot#114]
Hello Vincent,

Once again me with my Nobis stove. On the application, when the automatic mode is not enabled, I can control manually power (from 1 to 7) and fan speed (Off, 1 to 7, or PS, meaning linked to the selected power). At the moment, from HA, I can choose power (via climate entity), but not fan speed.

After a quick look at the diagnostic file (linked in #111), I think that it is related to function vent_front_set. Is it possible to enable access to this control?

Thanks in advance.

**Comment by vincentwolsink** [comment]
Hi @rvannunen. Looking at the diagnostics data the front fan control is not enabled for your stove. This might have something to do with the automatic mode. Can you try disabling automatic mode and reload the integration? See if that makes the control entity appear.

**Comment by rvannunen** [comment]
It works, I now get a climate entity to control fan speed.

Indeed, in the Nobis application, when auto mode is activated, controls for power level and fan speed are automatically hidden. As power level was nevertheless available in HA (even if integration was loaded with auto mode on), I didn't tried to reload with auto mode desactivated, but it works.

Thanks

**Comment by jipem01** [comment]
Hello Vincent,I never tried auto mode personally on Nobis, but if you would like to investigates more I could activate it and transfert associated diagnosis.

**Comment by rvannunen** [comment]
Sorry, I reopen this topic.

With the new climate entity which has appeared following reload with auto mode on, I am now able to **_set_** fan speed. However, I also have in the application visibility about real fan speed, which can be different of selected fan speed when operating in auto mode.

At the moment, this sensor is not visible in HA, I suppose because function name is vent_front2_get, and not vent_front2_get as code probably expects. I think it is the same issue you had in issue #44, with temp_air2_get vs. temp_air_get. Is it possible to get visibility on this value in HA?

Thanks

**Comment by vincentwolsink** [comment]
Can you please post a screenshot of how it looks in your app?

Also, Home Assistant supports very limited option in how fan speed etc can be displayed and controlled. It only supports one fan per climate entity and does not support any differences between selected and actual fan speed (I also wonder why there would be any, so please post a screenshot of your app 🙂 )

**Comment by rvannunen** [comment]
In fact, there are three tabs in the application:

1. Display informations: status of stove, current (real) power, current (real) temperature, and current (real) front fan speed. Button allows also to start/stop stove
![IMG_3085](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/146890510/33ca0ace-30c1-462d-b228-4a7fa6f39466)

2. Modify settings: it has two sets of commands depending on activation or not of auto mode:
- When auto mode is on: allows to set target temperature, manage auto mode (on/off) and manage powerful mode (on/off). In this case, power level and fan speed are automatically managed by stove, depending on gap between real temperature and target temperature
![IMG_3044](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/146890510/f6fee6b7-5713-4c8e-8e49-7afd5c1cb8c7)
- When auto mode is off: same commands as before, but allows also to set power level (1 to 7) and front fan speed (Off, 1 to 7, PS, that means linked to power level)
![IMG_3084](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/146890510/d9208f87-84c2-4967-8e09-16bfed0cfe30)

3. Manage schedule (4 programs allowing to automatically start or stop stove at given time on given days)

At the moment I find nearly all same functionalities in HA:
- First climate entity allows to start/stop stove, set target temperature, view current (real) temperature and set power level (named “mode de ventilation” = fan mode, but it is in fact the power which is managed)
![IMG_0052](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/146890510/81da4533-5b69-4945-834e-c3b3b18aaaa7)
- Second climate entity allows to control fan speed (but only part of the climate entity used is the dropdown to select fan speed, again “mode de ventilation”, rest of control is not used)
![IMG_0053](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/146890510/f89d865e-a689-4397-aa41-18d25c87f9a3)
- I get two separate switch to manage auto and powerfull mode and a sensor for current (real power) and another one for status
![IMG_0054](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/146890510/157a0741-342e-4297-8101-33b844db12f5)
The only missing information is the current (real) fan speed.

The reason why the current (real) fan speed and the target fan speed may differ is linked to the fact that the application keeps the last target fan speed in memory, even when auto mode is on, and stove could then modify itself the target fan speed. Same reasoning for current (real) power which may differ from target power. But as in HA I have two different entities (one climate entity and one sensor), this does not cause an issue.

Same thing could be done for fan speed: one sensor to display current (real) fan speed, and the climate entity to select the target fan speed. In fact, full climate entity is not needed, maybe a simple other kind of entity allowing to select value from dropdown list could be sufficient (an input_select? As I am quite new to HA, this I maybe a nonsense…).

**Comment by vincentwolsink** [comment]
Thanks for the clarification.

To comment on the use of climate entities for fans, this integration tries to be compatible with every stove configuration possible. Some have extra fans, some extra temperature sensors, some both. Depending on the features of your stove the climate entity will also have capabilities or setting temperatures (or in your case, not).

Also for simpler stoves (like mine) the power setting is coupled to the fan speed. And since Home Assistant does not support setting power for an climate entity, the main entity fan speed will indeed control power, which makes perfect sense for simple stoves, and sometimes a little bit less for more complex stove configurations. 🙂

What I can (and will) do is add extra sensors for the "real" fan speed for stoves that support it.

**Comment by rvannunen** [comment]
Thanks Vincent. I understand perfectly the need to ensure compatibility with all configurations.

I have tested the new version, it works perfectly and fits my need.

Thank you once again.
