### ISSUE TITLE
extra settings and stats ? 

### ISSUE THREAD

**Issue by silkyclouds** [vincentwolsink/home_assistant_micronova_agua_iot#115]
Hi @vincentwolsink,

I had to go through the (painful) process of configuring my stove technical settings lately as it was definitely putting too much pellets which resulted in heating problems. 

It lead me to start playing around with my jollu mec controller a little more, and it turns out a ton of settings are visible there I would like to see in home assistant. 

1. the usage stats (available without the technician code). As I understand I can create utility meters based on your integration, I am wondering if it could be possible to grab the stats that are inherent to the device, and which are reported using the remote controller
2. advanced settings, a ton of settings related to the different RPMs and such things are available un the advanced settings menu of the remote controller, while this should be a set and forget thing, I wonder if we could eventually get these settings to display inside HA for an easier configuration and follow-up of specific test results
3. Warnings : as you know. as soon the stove will display a warning (Eg: no more pellet), gaining access to the actualy manufacturer's controller is a must to bypass the warining upfront a next operation, is this something we could eventually do from within HA ? 

I know this is quite specific, but as I can see new features and sensors popping up, I wonder if these ones are somehow on the roadmap. 

Thanks ! :)

**Comment by vincentwolsink** [comment]
Hi @silkyclouds,

We are depending on the Agua IOT platform for this integration. I don't think anything from 1 and 2 is available. But you can always check the diagnostic file, it contains everything that is available for your stove. If you find anything interesting there let me know.

I don't understand your question in 3. If you are talking about the alarms, they are exposed via the alarms sensor entity.

**Comment by ArnisV** [comment]
3.
Is there a way remotly reset alarm?
Or auto reset alarm.

**Comment by vincentwolsink** [comment]
> Is there a way remotly reset alarm? Or auto reset alarm.

I currently do not see a possibility for that in the available registers. Can you do it from the vendor app?

**Comment by silkyclouds** [comment]
> > Is there a way remotly reset alarm? Or auto reset alarm.
> 
> I currently do not see a possibility for that in the available registers. Can you do it from the vendor app?

Well this is something that can be done from the vendor remote, but not from their app. It would be nice to be able to reset an alarm from inside HA, this would allow to restart a stove in an alarm state even if we don't have the damn working remote anymore ;)

**Comment by ArnisV** [comment]
> > > Is there a way remotly reset alarm? Or auto reset alarm.
> > 
> > 
> > I currently do not see a possibility for that in the available registers. Can you do it from the vendor app?
> 
> Well this is something that can be done from the vendor remote, but not from their app. It would be nice to be able to reset an alarm from inside HA, this would allow to restart a stove in an alarm state even if we don't have the damn working remote anymore ;)

well,
 what YOu mean vendor remote?
I was thinking to add ewelink relay to link stove start button. I have the stove at country hause and staring remotly now and then i fails. I also have camera to see what is going on.
normaly the scenay is when Im at the place:
1.alarm stars
2.after whilestarts  final cleaning ,cleans the pot blowing air and starts the fire.(at this point remotly you are helpless)
3. press start button, and alarm is removed.
4.  turn of and on stove
5. press start and stove starts new fire up. but its already burning and I dint sea any danger.
sorry my english

alias: alarm reset
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.centrometal_alarm
    for:
      hours: 0
      minutes: 2
      seconds: 0
    enabled: false
  - platform: device
    device_id: 5027a8cc301b18727409de94aa4e71f1
    domain: xiaomi_gateway3
    type: button_1
    action: hold
action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.sonoff_1001df8154_1
  - delay: "00:00:05"
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.sonoff_1001df8154_1
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.0x00158d00028c06dd_channel_1
  - delay: "00:00:04"
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.0x00158d00028c06dd_channel_1
  - delay: "00:00:10"
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.sonoff_1001df8154_1
  - delay: "00:00:05"
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.sonoff_1001df8154_1

**Comment by vincentwolsink** [comment]
> Well this is something that can be done from the vendor remote, but not from their app.

The stove remote does not use the AguaIOT cloud platform. Unfortunately it seems resetting alarms is not exposed via the cloud and thus I cannot implement it via this integration.

P.S. Maybe turning off and on the stove via HA would reset the alarm? It does for me.

**Comment by ArnisV** [comment]
can YOu shae script? for turning of and on .

**Comment by silkyclouds** [comment]
I believe @vincentwolsink refers to a simple smart switch that actually powers the stove off and on again ? 

I did not try this (yet) as my stove model tends to display an even worse message (blackout) when power goes away, but yeah, it's something to investigate.

**Comment by vincentwolsink** [comment]
No I mean just with the climate entity in HA.

**Comment by vincentwolsink** [comment]
I'm also thinking about creating a local solution, with an ESP32 directly connected to the stove, to bypass cloud dependency. But currently do not have the free time for that 😅

**Comment by ArnisV** [comment]
> I'm also thinking about creating a local solution, with an ESP32 directly connected to the stove, to bypass cloud dependency. But currently do not have the free time for that 😅

be carefull, i burned my esp, as comunication has serial one whire. no rx tx. I wanted to integrade with duepi-evo. 
 my stove has for  micronova agua  ground, serial and 12v

**Comment by jipem01** [comment]
For bypassing the cloud, we could also try to communicate with the stove by bluetooth (natively supported by many agua communication modules).I've read some docs how to spy an app bluetooth communication on android but didn't add time to really try currently...For DIY controller, i've seen in the web project using arduino replacing the agua communication modules. It seems more flexible and powerfull, but you totally loose communication with agua cloud, so the vendor app become useless. And it seems it could only work if your stove use an additional communication moduled. On recent stoves it's directly integrated on main motherboard (as mine)

**Comment by silkyclouds** [comment]
> > I'm also thinking about creating a local solution, with an ESP32 directly connected to the stove, to bypass cloud dependency. But currently do not have the free time for that 😅
> 
> be carefull, i burned my esp, as comunication has serial one whire. no rx tx. I wanted to integrade with duepi-evo. my stove has for micronova agua ground, serial and 12v

I personally own one fo these ESP devices at philibertC built. It's supposed to avoid people to buy the (expensive) micronova wifi module + avoid them to be online in order to get it to work (so it will work out of micronova's cloud, which may be interrupted one day). 

If you want me to help you try to get that one to work, we might have a look at it, but I eneded up going back to your integration and my (official) wifi module for a simple reason, it wasn't plug and play t all, and I only had 3 wires instead of 4 on my stove controller, which made it really complex to get working.

**Comment by ArnisV** [comment]
I think this integration works perfect for my needs.
plus added start button now I can fully control my stove .
only thing is that confuses real power name is FAN 
![Screenshot_2023-12-30-06-21-17-035_io homeassistant companion androie](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/3842735/81cf7749-c19e-4662-89be-c58e6932c016)

**Comment by silkyclouds** [comment]
regarding the warnings, as there is currently no way to get rid of the alarms without using the stove remote controller, and because I keep cleaning it, and forget to press the damn button on the damn remote, I wrote a stupid automation that will remind me every 30 minutes that the alarm is still on, if one of the alarms is on : 

````
alias: Notification - Alertes Insert à Pellets
description: Envoie une notification toutes les 30 minutes en cas d'alertes spécifiques de l'insert à pellets
trigger:
  - platform: state
    entity_id: sensor.readable_device_status
    to:
      - 'Alerte: Plus de pellet'
      - 'Alerte: Nettoyer brasier'
  - platform: time_pattern
    minutes: '/30'
condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: sensor.readable_device_status
        state: 'Alerte: Plus de pellet'
      - condition: state
        entity_id: sensor.readable_device_status
        state: 'Alerte: Nettoyer brasier'
action:
  - service: notify.groupe_de_notifications_famille
    data:
      message: "Alerte Insert à Pellets: {{ states('sensor.readable_device_status') }}"
mode: single
````

**Comment by CBK482** [comment]
Dear,

I have a nobis H17 V SHAPE attached to the radiator system.
I love this integration, but I miss some parameters, 
I would like to follow the following extra parameters

- Water pressure (to know when I have to fill up)
- Outgoing Water temperature
- Water pump activity
- delta pressure Brazier (autocleaning)
- Extractor fan.

I manually added the following to const.py and it works fine.
Would it be possible to add to the next release?


    AguaIOTSensorEntityDescription(
        key="pres_h2o_get",
        name="Pres. H2O",
        native_unit_of_measurement=UnitOfPressure.BAR,
        state_class=SensorStateClass.MEASUREMENT,
        device_class=SensorDeviceClass.PRESSURE,
    ),
    AguaIOTSensorEntityDescription(
        key="pascal_get",
        name="Brazier Pressure",
        native_unit_of_measurement=UnitOfPressure.PA,
        state_class=SensorStateClass.MEASUREMENT,
        device_class=SensorDeviceClass.PRESSURE,
    ),
    AguaIOTSensorEntityDescription(
        key="giri_estrattore_get",
        name="Extractor Fan",
        icon="mdi:gauge",
        native_unit_of_measurement=REVOLUTIONS_PER_MINUTE,
        state_class=SensorStateClass.MEASUREMENT,
        device_class=None
    ),
    AguaIOTSensorEntityDescription(
        key="pomp_h2o_get",
        name="Pump H20",
        icon="mdi:gauge",
        native_unit_of_measurement=None,
        state_class=None,
        device_class=None,
    ),
    AguaIOTSensorEntityDescription(
        key="temp_h2o_mandata_get",
        name="H2O Delivery",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        state_class=SensorStateClass.MEASUREMENT,
        device_class=SensorDeviceClass.TEMPERATURE,
    ),

**Comment by vincentwolsink** [comment]
@CBK482 Sure! Can you also please provide me your diagnostic file? So I can include it in testing fixtures.

**Comment by CBK482** [comment]
[config_entry-aguaiot-0ec8a85bb74f9ab1bda7235a34bdae63 (1).json](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/files/15133322/config_entry-aguaiot-0ec8a85bb74f9ab1bda7235a34bdae63.1.json)
Hereby my config file (stove is running ;-) )

**Comment by giuliovialetto** [comment]
> For bypassing the cloud, we could also try to communicate with the stove by bluetooth (natively supported by many agua communication modules).I've read some docs how to spy an app bluetooth communication on android but didn't add time to really try currently...For DIY controller, i've seen in the web project using arduino replacing the agua communication modules. It seems more flexible and powerfull, but you totally loose communication with agua cloud, so the vendor app become useless. And it seems it could only work if your stove use an additional communication moduled. On recent stoves it's directly integrated on main motherboard (as mine)

@jipem01 have you ever tried to control the stove by bluetooth and/or directly with wifi?

**Comment by CBK482** [comment]
I guess this would be a complete separate integration?

**Comment by silkyclouds** [comment]
> I guess this would be a complete separate integration?

As far as I can see this topic was closed by @vincentwolsink so I'm unsure if this will actually happen. But I agree on one thing, if we were able to figure out ways to easdily plug ESP devices to our stoves serial ports, we would get rid of : 

1. the overpriced micronova devices (which are ESP based anyway)
2. the need to make use of their cloud (which could be terminated at any time) 

It would be a full WIN.

**Comment by CBK482** [comment]
It shouldn't be to hard to put a "logger" on the serial communication. I'll try to get into it (using an ESP32 ;-) )

**Comment by vincentwolsink** [comment]
There are several initiatives/solutions to control your stove locally available already. (You won't be able to use them together with this integration)

https://esphome.io/components/micronova.html
https://github.com/eni23/micronova-controller
https://github.com/fabrizioromanelli/Pellet-Stove-Control
