### ISSUE TITLE
Temperatur

### ISSUE THREAD

**Issue by darikroni** [vincentwolsink/home_assistant_micronova_agua_iot#123]
I can't display the temperature in C° for selection.

**Comment by vincentwolsink** [comment]
I need a lot more context to be able to help you. Don't you see a temperature at all? Is the temperature in Fahrenheit? Where do you expect the temperature to be displayed?

Please send a bit more description, a screenshot and your diagnostics file.

**Comment by darikroni** [comment]
Hi.I see the temperatur only in fahreinheit.Thanks for your help.--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 31.12.23, 10:20 schrieb Vincent Wolsink ***@***.***>:

   
  I need a lot more context to be able to help you. Don't you see a temperature at all? Is the temperature in Fahrenheit? Where do you expect the temperature to be displayed? 
  Please send a bit more description, a screenshot and your diagnostics file.

**Comment by vincentwolsink** [comment]
Make sure your home assistant temperature notation is set to celsius in the [general settings](https://my.home-assistant.io/redirect/general/).

**Comment by darikroni** [comment]
Thank you very much.And i wish you a happy new year.--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 31.12.23, 11:31 schrieb Vincent Wolsink ***@***.***>:

   
  Make sure your home assistant temperature notation is set to celsius in the general settings.
