### ISSUE TITLE
Unknown Agua IOT error: Error while fetching device information

### ISSUE THREAD

**Issue by merlino1975** [vincentwolsink/home_assistant_micronova_agua_iot#124]
Home Assistant Core
Unknown Agua IOT error: Error while fetching device information
09:13:20 – (ERRORE) Micronova Agua IOT (integrazione personalizzata) - il messaggio si è verificato per la prima volta alle 31 dicembre 2023 alle ore 18:59:57 e compare 13 volte
/config/custom_components/aguaiot/aguaiot.py:304: RuntimeWarning: coroutine 'aguaiot.do_refresh_token' was never awaited self.do_refresh_token()
1 gennaio 2024 alle ore 16:43:00 – (AVVISO) Micronova Agua IOT (integrazione personalizzata)
Error handling request
31 dicembre 2023 alle ore 18:42:53 – (ERRORE) /usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py
The system cannot restart because the configuration is not valid: Invalid config for 'http' at configuration.yaml, line 18: not a valid value 'http->trusted_proxies->1', got '172.30.232.0/16'
31 dicembre 2023 alle ore 18:42:53 – (ERRORE) Home Assistant Core Integration
TemplateError('UndefinedError: 'default' is undefined') while processing template 'Template<template=({{ state_attr('weather.home', 'temperature')|float(default-0) }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.temperatura_esterna'
31 dicembre 2023 alle ore 16:42:29 – (ERRORE) Template
Error while processing template: Template<template=({{ state_attr('weather.home', 'temperature')|float(default-0) }}) renders=2>
31 dicembre 2023 alle ore 16:42:29 – (ERRORE) helpers/template.py

 hassio on virtualmachine ..hardware nas synology

**Comment by vincentwolsink** [comment]
When did this issue start occurring? Is it still happening? Did you try to restart HA? Is the vendor app working?
There is a lot going on in the pasted logfiles. I see several different timestamps, errors about a misconfigured proxy.

**Comment by merlino1975** [comment]
yes, sorry, I solved all the other problems, the reverse proxy and the external temperature sensor were problems that I was aware of and solved today.
The only problem I have left is that of the micronova agua iot..
The only difference is that I went from installing Home Assistant Core on Docker (NAS Synology) to Home Assistant OS on VMW (Virtual Machine) on NAS Synology.
I already tried restarting... the app works

**Comment by vincentwolsink** [comment]
At what point does it fail, during configuration? If you show the full logs, is there some more information? What is your stove brand again?

**Comment by merlino1975** [comment]
It actually looks like I've completed the setup.  I see all the entities and I have the connections on the dashboard... where can I see the complete logs?  the stove is a unique nobis fire 10

**Comment by vincentwolsink** [comment]
If everything is working then there is no issue. Sometimes the cloud api does not respond and that throws this error.
