### ISSUE TITLE
Status display is not being interpreted correctly

### ISSUE THREAD

**Issue by Moeros** [vincentwolsink/home_assistant_micronova_agua_iot#126]
Hello, 

I own a Piazetta hybrid stove. Unfortunately, the status display is not being interpreted correctly. For example, the status "Hybrid" or operation with wood is missing. Is it possible to analyze and interpret these statuses?

Thank your for the help!

**Comment by vincentwolsink** [comment]
Hi @Moeros. I can see if I can implement those for your stove. Can you send the diagnostics file of your stove and a screenshot from the vendor app that shows what you are talking about?

**Comment by Moeros** [comment]
Hi @vincentwolsink I'm new in Home Assistant an i hope you mean this diagnostic file.

[config_entry-fritz-347bb868fa569388b117c67c928dfc23.json.txt](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/files/13813419/config_entry-fritz-347bb868fa569388b117c67c928dfc23.json.txt)

![Screenshot_20240102_204941_MyPiazzetta](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/37508901/e0a6ed45-6d30-4abd-a51f-0958ddfa886b)

At this moment the stove is working with wood.

I have tried to locate the part in the code where this is being evaluated, but without success.

**Comment by Moeros** [comment]
![Screenshot_20240102_205719_MyPiazzetta](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/37508901/75669493-bb17-4f36-9b88-764cc4949213)

**Comment by vincentwolsink** [comment]
You send your diagnostics file for your Fritzbox integration (I deleted it from your post).
Press the button below, click the three dots next to MyPiazzetta (or something) and click "Download diagnostics".

[![Open your Home Assistant instance and show an integration.](https://my.home-assistant.io/badges/integration.svg)](https://my.home-assistant.io/redirect/integration/?domain=aguaiot)

**Comment by Moeros** [comment]
[config_entry-aguaiot-105d2b0215fa9760ab954adbcc0591f3.json.txt](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/files/13813655/config_entry-aguaiot-105d2b0215fa9760ab954adbcc0591f3.json.txt)

omg that was a upload-mistake! Thank you for deleting it!!!

**Comment by Moeros** [comment]
WORKING
LIGHTING
AWAITING FLAME
Heizen
PELLET LOAD
OFF
FINAL CLEANING
ASHPAN CLEANING

These are available

**Comment by vincentwolsink** [comment]
The status above are available via the status sensor. The fuel type I can add as an extra sensor. Anything else you are missing?

**Comment by Moeros** [comment]
The extra sensor would be fine and the status hybrid.

**Comment by vincentwolsink** [comment]
Available in [v0.3.7](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/releases/tag/v0.3.7)

**Comment by Moeros** [comment]
Thank you very much!

It works great!
