### ISSUE TITLE
Desired Temperature and Current temperature sensor

### ISSUE THREAD

**Issue by electro575** [vincentwolsink/home_assistant_micronova_agua_iot#128]
Hi,

Thank you a lot for this plugin HA.

I'm asking if it's possible as MyPiazzetta app to **implement the status of desired Temperature value** ?
And add the possibility to change this value.

Too, is it possible to **implement the current temperature value of sensor** ?

I have add your project to the path ~/.homeassistant/custom_components.

So, i don't have added the folder "fixtures" which contain : piazzetta_hybrid.json.
What do this file and what's the good manner to add your project ?

Add to this thread : i often have this log but i don't know why !
`ERROR (MainThread) [custom_components.aguaiot] Unknown Agua IOT error: Error while fetching device information`

But the rest work perfectly, thanks a lot

**Comment by vincentwolsink** [comment]
Hi @electro575,

The target and current temperature should be accessible via the main climate entity for your stove.
If you don't see it there, please upload your diagnostics file here.

You don't need the fixtures. I would recommend you to install the plugin via [HACS ](https://hacs.xyz/) instead of manually, this also allows for easy updates etc.

**Comment by electro575** [comment]
Hi,
I have looking for climate under developer tools -> services -> climate.set_temperature
And, when i try to do apply this HA setting, i have this error on Micronova.

https://debian-facile.org/paste-3ABCB5382F

Here full diagnostic file.
[diagnostic file](https://debian-facile.org/paste-AA9B6A3A9B).

I'm agree with you for HACS, but i love manually update too.

**Comment by vincentwolsink** [comment]
I tested the integration with the fixture data you provided (the diagnostics file), and everything works fine for me. I can see main and target temperature. I can also set the temperature via `climate.set_temperature`.

Can you post the service call you are trying to do? Either in yaml format or a screenshot?

**Comment by electro575** [comment]
Screenshot of the service called.

![Capture d’écran du 2024-01-26 08-51-10](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/33623503/0558445f-0707-4c2b-918a-dd0d0590371d)

Curious, after call the service, the temperature appear in the widget in lovelace..

But when i try to change this temperature, i have this error log.

`ERROR (MainThread) [custom_components.aguaiot.climate] Failed to set temperature, error: Error while trying to set: key=temp_air_set value=21`

But i don't understand why the API server return this log again and again. And with the app mypiazzetta, it's the same, i have often an error when i want to access to my heating system. Why ?

`ERROR (MainThread) [custom_components.aguaiot] Unknown Agua IOT error: Error while fetching device information`

My Lovelace.

![Capture d’écran du 2024-01-26 08-57-24](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/33623503/7b4b484a-405b-4baf-8acb-fdc9c634260c)

**Comment by vincentwolsink** [comment]
@electro575 Could it be that your stove has a bad wifi connection?

**Comment by electro575** [comment]
I have reboot my router and the bridge works perfectly now.

Your custom component too.

Sorry ! And thank you a lot for your work
