### ISSUE TITLE
Unknown real power with Easy Connect Plus

### ISSUE THREAD

**Issue by vymak** [vincentwolsink/home_assistant_micronova_agua_iot#131]
Hello,
thanks for the cool integration into Home assistant. 

Everything works properly except for one little thing. 
I see the real power as "**unknown**" for me. 

If this little bug could be removed it would be perfect.

![image](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/3403705/03f4610b-a704-4352-9aad-f017948e843e)

**Comment by vincentwolsink** [comment]
Hi @vymak, can you please send your diagnostic file for the integration. I will then see why it is showing unknown.

**Comment by vymak** [comment]
Hi @vincentwolsink , i am sending a file with diagnostic information.

[config_entry-aguaiot-813ea2bf798e74089aa9d298a15d3cd4.json (1).txt](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/files/14151184/config_entry-aguaiot-813ea2bf798e74089aa9d298a15d3cd4.json.1.txt)

**Comment by vincentwolsink** [comment]
It seems this measurement is not available for your stove. Is it available in the official app?

**Comment by vincentwolsink** [comment]
Please install v0.3.8, turn on debug logging, reload integration and send the output to me :)

**Comment by vincentwolsink** [comment]
Please try [v0.4.0-beta1](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/releases/tag/v0.4.0-beta1)

**Comment by vymak** [comment]
@vincentwolsink 
Thanks a lot. At first glance it looks fine, but my boiler is now switched off so I can't judge whether it shows the real power correctly. However, the real power value is the same in HA and Easy Connect. Tomorrow, when it warms up, I will confirm that it works :)

![image](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/3403705/1e91c10d-4ca5-4a34-98c0-05ae4823ede6)

**Comment by vymak** [comment]
@vincentwolsink it works 💯 
![image](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/3403705/a01fb2a3-04cd-471d-9e2b-fa8fe16bf9bf)
