### ISSUE TITLE
problem with stove entity and nodered

### ISSUE THREAD

**Issue by merlino1975** [vincentwolsink/home_assistant_micronova_agua_iot#134]
Using a nodered flow I can through Alexa turn the stove on and off.
The problem is that, if I spend the stove, everything is perfect.
If I turn on the stove, in addition to turning it on in "fullpower" and "auto" mode, it should also theoretically keep the same settings that I gave it when it was turned on, set a tapo c200 camera to "privacy" and start the alarm siren.
very strange.
So I don't know if it's a flow problem, a homeassistant problem or a mocronova iot problem.
And at this point I don't know if it's more of a report of a problem or a request for help. Or maybe both at the same time
thanks!

**Comment by merlino1975** [comment]
update:
now, after the last update micronova the flow of nodered doesn't work..

**Comment by merlino1975** [comment]
HI...After the last updates flow doesn't work.. I've the debug message:
"HomeAssistantError: Entity climate.stufa_salotto_vent_front does not support this service."

it seems that the start stove command is no longer able to do it but it tries to start the fans (I in the call service) I put another entity.
Let's try to look at the problem from another point of view:
but I'm in node red, what service should I call? That is, what is the right entity among those I have to start the stove? when I call the service I can tell them "turn-off" or "turn-on" (call service turn on or turn off)
Thank you

**Comment by vincentwolsink** [comment]
> "HomeAssistantError: Entity climate.stufa_salotto_vent_front does not support this service."

This error explains it. You are trying to turn on the "vent front", which is a fan. Try calling the turn on service on the main climate entity of the stove.

**Comment by merlino1975** [comment]
But I think of do it..please you say me the correct identity..may be i mistake...but in the call service wich i choose  i m sure are not vent front..it s this i don't understand

**Comment by merlino1975** [comment]
Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: custom_components.aguaiot
Source: custom_components/aguaiot/__init__.py:79
Integration: Micronova Agua IOT (documentation, issues)
First occurred: 11:37:15 (1 occurrences)
Last logged: 11:37:15

Unknown Agua IOT error: Error while fetching device information

this is the error
