### ISSUE TITLE
Ravelli Cloud issue

### ISSUE THREAD

**Issue by Nayou09** [vincentwolsink/home_assistant_micronova_agua_iot#139]
Hi !
I’ve a Ravelli Chiara S with wifi module.
I’m trying to enroll the stove in HA, but can’t manage. It say wrong credential, but I’ve made a test on the web API, and they’re working…
Thx a lot 😊

**Comment by vincentwolsink** [comment]
Hi @Nayou09. What is the error in the HA logs? And what is the api url that you tested on?

**Comment by Nayou09** [comment]
Hi,
The logs are:
`Logger: custom_components.aguaiot.config_flow
Source: custom_components/aguaiot/config_flow.py:85
Integration: Micronova Agua IOT (documentation, issues)
First occurred: 21:39:30 (2 occurrences)
Last logged: 21:39:49

Agua IOT Unauthorized: Failed to login, please check credentials `


Url of the API
https://ravelli.cloudwinet.it/Login.aspx

**Comment by vincentwolsink** [comment]
Your stove does not use the Micronova AguaIOT platform but the WiNet platform for app control.

So unfortunately it is not compatible with this integration. For reference, exactly which Ravelli app are you using?
