### ISSUE TITLE
Smoke temp should not be an extra attribute

### ISSUE THREAD

**Issue by jipem01** [vincentwolsink/home_assistant_micronova_agua_iot#14]
As mentionned in HA doc, entities extra attribute should not be value who change to often, as it force saving the whole state of the entity each time and could flood the database.
[https://developers.home-assistant.io/docs/core/entity/](https://developers.home-assistant.io/docs/core/entity/)

```
danger

Entities that generate a significant amount of state changes can quickly increase the size of the database when the extra_state_attributes also change frequently. Minimize the number of extra_state_attributes for these entities by removing non-critical attributes or creating additional sensor entities.
```

Considering list of extra attributes :

-   ATTR_DEVICE_ALARM
-   ATTR_DEVICE_STATUS
-   ATTR_HUMAN_DEVICE_STATUS
-   ATTR_SMOKE_TEMP
-   ATTR_REAL_POWER

We should consider that smoke temp will change at each reading. So using an extra attribute is not a good idea. Therefore, it will be better to move it as a sensor. I'm working on it (plus additionals sensors entities).

**Comment by rvannunen** [comment]
Thanks a lot Vincent, working perfectly!
