### ISSUE TITLE
NOBIS

### ISSUE THREAD

**Issue by thebadboyltz** [vincentwolsink/home_assistant_micronova_agua_iot#141]
Hello, first of all thank you for your work. I have a NOBIS stove, in the shutdown phase it takes a certain amount of time and it happens that when we send the shutdown command it does not work (the NOBIS cloud is capricious. Is it possible that when we trigger the stop mode the thermosat in HA changes color In my IOS homekit application the color changes to black when the stop command is triggered.

![IMG_9609](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/153684851/645291c8-ef51-4614-867f-2c6b5e7dee29)
![IMG_9610](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/153684851/c4ab5a29-c6a8-4c59-b5db-6b1f65dcf83b)

**Comment by vincentwolsink** [comment]
Hi @thebadboyltz. I can make it go to off if the stove has a specific status when it is turning off (for example `FINAL CLEANING` for my stove). Please check the status sensor at the time the stove is turning off and let me know.

**Comment by thebadboyltz** [comment]
this is what status returns as information. OFF is off, START is the start-up phase, WORK is when the stove is operating and STOP is when it is in the shutdown phase. It would be great to be able to display the different colors in the thermostat depending on the status
![IMG_9611](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/153684851/a7508c68-a519-4861-8439-1cba5b8f8c2a)
![IMG_9612](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/153684851/f3cbd420-5034-4d3b-b535-67f7de504669)
![IMG_9613](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/153684851/4115698d-3908-4928-b96c-402573b4da44)
![IMG_9614](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/153684851/8cdce598-a0b2-4718-88c3-cfbb15ce10c9)

**Comment by vincentwolsink** [comment]
The thermostat in HA does not support multiple colors or multiple fans. Unfortunately we have to work with the features available. That is why a lot of things have different entities.

I can make the thermostat go to off mode if the stove is in STOP. That way you can see if the command was successful and the stove is shutting down.

**Comment by thebadboyltz** [comment]
if you know how to do this it is an excellent and most important thing.

for the fan function in addition to the power control is this possible?

**Comment by vincentwolsink** [comment]
> for the fan function in addition to the power control is this possible?

No. Home assistant does not support multiple fan controls on one climate entity.

I will release a new version with improved status mapping in a few minutes.

**Comment by thebadboyltz** [comment]
thank you, it works 100%
