### ISSUE TITLE
No climate control with Wi-Phire board since V0.4.4 release

### ISSUE THREAD

**Issue by FR2776** [vincentwolsink/home_assistant_micronova_agua_iot#144]
There is no more climate control with Wi-Phire board since V0.4.4 release. other sensors works well

**Comment by vincentwolsink** [comment]
Hi @FR2776, can you please share any relevant errors in the home assistant error logs? And also your diagnostics file.

**Comment by CR3304** [comment]
I'm having same issue. The controller for a GO HEAT has dissapeared. The smoke, status and other sensors works fine

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.5.0",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.12.2",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Madrid",
    "os_name": "Linux",
    "os_version": "6.1.73-haos-raspi",
    "supervisor": "2024.04.4",
    "host_os": "Home Assistant OS 12.2",
    "docker_version": "25.0.5",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "meross_cloud": {
      "documentation": "https://www.home-assistant.io/components/meross_cloud",
      "version": "1.3.0",
      "requirements": [
        "meross_iot==0.4.7.0"
      ]
    },
    "hacs": {
      "documentation": "https://hacs.xyz/docs/configuration/start",
      "version": "1.34.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "scheduler": {
      "documentation": "https://github.com/nielsfaber/scheduler-component",
      "version": "v0.0.0",
      "requirements": []
    },
    "aguaiot": {
      "documentation": "https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/",
      "version": "0.4.4",
      "requirements": [
        "httpx",
        "simpleeval"
      ]
    },
    "sonoff": {
      "documentation": "https://github.com/AlexxIT/SonoffLAN",
      "version": "3.7.3",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    },
    "localtuya": {
      "documentation": "https://github.com/rospogrigio/localtuya/",
      "version": "5.2.1",
      "requirements": []
    },
    "midea_ac": {
      "documentation": "https://github.com/mill1000/midea-ac-py",
      "version": "2024.3.2",
      "requirements": [
        "msmart-ng>=2024.3.2"
      ]
    },
    "nodered": {
      "documentation": "https://zachowj.github.io/node-red-contrib-home-assistant-websocket/guide/custom_integration/",
      "version": "3.1.7",
      "requirements": []
    }
  },
  "integration_manifest": {
    "domain": "aguaiot",
    "name": "Micronova Agua IOT",
    "codeowners": [
      "@vincentwolsink"
    ],
    "config_flow": true,
    "dependencies": [],
    "documentation": "https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/",
    "integration_type": "hub",
    "iot_class": "cloud_polling",
    "issue_tracker": "https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/issues",
    "requirements": [
      "httpx",
      "simpleeval"
    ],
    "version": "0.4.4",
    "is_built_in": false
  },
  "data": {
    "entry": {
      "entry_id": "1d085e1a12a43ce0a899f8f88aee66fc",
      "version": 1,
      "minor_version": 1,
      "domain": "aguaiot",
      "title": "GO HEAT",
      "data": {
        "email": "**REDACTED**",
        "password": "**REDACTED**",
        "uuid": "ac81c1a2-0707-11ef-b30c-d83add4e5932",
        "api_url": "https://amg.agua-iot.com",
        "customer_code": "859435",
        "login_api_url": null
      },
      "options": {},
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": null,
      "disabled_by": null
    },
    "devices": {
      "Sal\u00f3n ": {
        "alarms_enable": {
          "app_image_name": "default",
          "reg_key": "alarms_enable",
          "reg_name": "Alarms_enable",
          "reg_name_app": "Alarms enable",
          "reg_key_group": "alarms",
          "reg_type": "ENABLE",
          "offset": 33,
          "eeprom": false,
          "is_word": false,
          "big_endian": false,
          "formula": "#",
          "formula_inverse": "#",
          "format_string": "{0}",
          "set_min": 0,
          "set_max": 65535,
          "readonly": false,
          "mask": 65535,
          "is_hex": false,
          "is_temperature": false,
          "use_app": true,
          "display_dashboard": false,
          "display_manage": false,
          "display_info": false,
          "use_cat": true,
          "display_order": 0,
          "step": 1,
          "use_history": true,
          "use_history_output": true,
          "with_sign": false,
          "from_char_code": false,
          "notify_on_change": false,
          "tab_group": "",
          "is_test": false,
          "enable_val": [
            {
              "value": 8
            },
            {
              "value": 9
            }
          ],
          "value_raw": "0",
          "value": 0
        },
        "alarms_get": {
          "app_image_name": "alarms_get",
          "reg_key": "alarms_get",
          "reg_name": "Allarmi",
          "reg_name_app": "Allarmi",
          "reg_key_group": "alarms",
          "reg_type": "GET",
          "offset": 99,
          "eeprom": false,
          "is_word": false,
          "big_endian": false,
          "formula": "#",
          "formula_inverse": "#",
          "format_string": "{0}",
          "set_min": 0,
          "set_max": 255,
          "readonly": false,
          "mask": 65535,
          "is_hex": false,
          "is_temperature": false,
          "use_app": true,
          "display_dashboard": false,
          "display_manage": false,
          "display_info": false,
          "use_cat": true,
          "display_order": 0,
          "step": 1,
          "use_history": true,
          "use_history_output": true,
          "with_sign": false,
          "from_char_code": false,
          "notify_on_change": false,
          "is_test": false,
          "value_raw": "0",
          "value": 0
        },
        "power_set": {
          "app_image_name": "power_set",
          "reg_key": "power_set",
          "reg_name": "Set Potenza",
          "reg_name_app": "Potenza",
          "reg_key_group": "power",
          "reg_type": "SET",
          "offset": 32816,
          "eeprom": true,
          "is_word": false,
          "big_endian": false,
          "formula": "#",
          "formula_inverse": "#",
          "format_string": "{0}",
          "set_min": 1,
          "set_max": 5,
          "readonly": false,
          "mask": 65535,
          "is_hex": false,
          "is_temperature": false,
          "use_app": true,
          "display_dashboard": false,
          "display_manage": true,
          "display_info": false,
          "use_cat": true,
          "display_order": 0,
          "step": 1,
          "use_history": true,
          "use_history_output": true,
          "with_sign": false,
          "from_char_code": false,
          "notify_on_change": false,
          "is_test": false,
          "value_raw": "1",
          "value": 1
        },
        "status_get": {
          "app_image_name": "status_get",
          "reg_key": "status_get",
          "reg_name": "Stato",
          "reg_name_app": "Stato",
          "reg_key_group": "status",
          "reg_type": "GET",
          "offset": 33,
          "eeprom": false,
          "is_word": false,
          "big_endian": false,
          "formula": "#",
          "formula_inverse": "#",
          "format_string": "{0}",
          "set_min": 0,
          "set_max": 255,
          "readonly": false,
          "mask": 65535,
          "is_hex": false,
          "is_temperature": false,
          "use_app": true,
          "display_dashboard": true,
          "display_manage": false,
          "display_info": true,
          "use_cat": true,
          "display_order": 0,
          "step": 1,
          "use_history": true,
          "use_history_output": true,
          "with_sign": false,
          "from_char_code": false,
          "notify_on_change": false,
          "is_test": false,
          "value_raw": "0",
          "value": 0
        },
        "status_managed_get": {
          "app_image_name": "status_managed_get",
          "reg_key": "status_managed_get",
          "reg_name": "Stato Gestito",
          "reg_name_app": "Stato Gestito",
          "reg_key_group": "status_managed",
          "reg_type": "GET",
          "offset": 232,
          "eeprom": false,
          "is_word": false,
          "big_endian": false,
          "formula": "#",
          "formula_inverse": "#",
          "format_string": "{0}",
          "set_min": 0,
          "set_max": 255,
          "readonly": false,
          "mask": 65535,
          "is_hex": false,
          "is_temperature": false,
          "use_app": true,
          "display_dashboard": false,
          "display_manage": false,
          "display_info": false,
          "use_cat": true,
          "display_order": 0,
          "step": 1,
          "use_history": true,
          "use_history_output": true,
          "with_sign": false,
          "from_char_code": false,
          "notify_on_change": false,
          "is_test": false,
          "enc_val": [
            {
              "value": 85,
              "lang": "BHS",
              "description": "ON"
            },
            {
              "value": 85,
              "lang": "DEU",
              "description": "ON"
            },
            {
              "value": 85,
              "lang": "ENG",
              "description": "ON"
            },
            {
              "value": 85,
              "lang": "FRE",
              "description": "ON"
            },
            {
              "value": 85,
              "lang": "ITA",
              "description": "ON"
            },
            {
              "value": 85,
              "lang": "NLD",
              "description": "ON"
            },
            {
              "value": 85,
              "lang": "PRT",
              "description": "ON"
            },
            {
              "value": 85,
              "lang": "SPA",
              "description": "ON"
            },
            {
              "value": 170,
              "lang": "BHS",
              "description": "OFF"
            },
            {
              "value": 170,
              "lang": "DEU",
              "description": "OFF"
            },
            {
              "value": 170,
              "lang": "ENG",
              "description": "OFF"
            },
            {
              "value": 170,
              "lang": "FRE",
              "description": "OFF"
            },
            {
              "value": 170,
              "lang": "ITA",
              "description": "OFF"
            },
            {
              "value": 170,
              "lang": "NLD",
              "description": "OFF"
            },
            {
              "value": 170,
              "lang": "PRT",
              "description": "OFF"
            },
            {
              "value": 170,
              "lang": "SPA",
              "description": "OFF"
            }
          ],
          "value_raw": "0",
          "value": 0
        },
        "status_managed_off_enable": {
          "app_image_name": "status_managed_off_enable",
          "reg_key": "status_managed_off_enable",
          "reg_name": "OFF",
          "reg_name_app": "OFF",
          "reg_key_group": "status_managed_off",
          "reg_type": "ENABLE",
          "offset": 33,
          "eeprom": false,
          "is_word": false,
          "big_endian": false,
          "formula": "#",
          "formula_inverse": "#",
          "format_string": "{0}",
          "set_min": 0,
          "set_max": 65535,
          "readonly": false,
          "mask": 65535,
          "is_hex": false,
          "is_temperature": false,
          "use_app": true,
          "display_dashboard": false,
          "display_manage": false,
          "display_info": false,
          "use_cat": true,
          "display_order": 0,
          "step": 1,
          "use_history": true,
          "use_history_output": true,
          "with_sign": false,
          "from_char_code": false,
          "notify_on_change": false,
          "is_test": false,
          "enable_val": [
            {
              "value": 1
            },
            {
              "value": 2
            },
            {
              "value": 3
            },
            {
              "value": 4
            },
            {
              "value": 5
            },
            {
              "value": 7
            }
          ],
          "value_raw": "0",
          "value": 0
        },
        "status_managed_on_enable": {
          "app_image_name": "status_managed_on_enable",
          "reg_key": "status_managed_on_enable",
          "reg_name": "ON",
          "reg_name_app": "ON",
          "reg_key_group": "status_managed_on",
          "reg_type": "ENABLE",
          "offset": 33,
          "eeprom": false,
          "is_word": false,
          "big_endian": false,
          "formula": "#",
          "formula_inverse": "#",
          "format_string": "{0}",
          "set_min": 0,
          "set_max": 65535,
          "readonly": false,
          "mask": 65535,
          "is_hex": false,
          "is_temperature": false,
          "use_app": true,
          "display_dashboard": false,
          "display_manage": false,
          "display_info": false,
          "use_cat": true,
          "display_order": 0,
          "step": 1,
          "use_history": true,
          "use_history_output": true,
          "with_sign": false,
          "from_char_code": false,
          "notify_on_change": false,
          "is_test": false,
          "enable_val": [
            {
              "value": 0
            }
          ],
          "value_raw": "0",
          "value": 0
        },
        "temp_air_get": {
          "app_image_name": "temp_air_get",
          "reg_key": "temp_air_get",
          "reg_name": "Temperatura Ambiente",
          "reg_name_app": "Temp. ambiente",
          "reg_key_group": "temp_air",
          "reg_type": "GET",
          "offset": 1,
          "eeprom": false,
          "is_word": false,
          "big_endian": false,
          "formula": "#/2",
          "formula_inverse": "#*2",
          "format_string": "{0}",
          "set_min": 0,
          "set_max": 255,
          "readonly": false,
          "mask": 65535,
          "is_hex": false,
          "is_temperature": false,
          "use_app": true,
          "display_dashboard": true,
          "display_manage": false,
          "display_info": false,
          "use_cat": true,
          "display_order": 0,
          "step": 1,
          "use_history": true,
          "use_history_output": true,
          "with_sign": false,
          "from_char_code": false,
          "notify_on_change": false,
          "is_test": false,
          "value_raw": "33",
          "value": 16.5
        },
        "temp_air_set": {
          "app_image_name": "temp_air_set",
          "reg_key": "temp_air_set",
          "reg_name": "Set Temperatura Ambiente",
          "reg_name_app": "Temp. ambiente",
          "reg_key_group": "temp_air",
          "reg_type": "SET",
          "offset": 32817,
          "eeprom": true,
          "is_word": false,
          "big_endian": false,
          "formula": "#/2",
          "formula_inverse": "#*2",
          "format_string": "{0}",
          "set_min": 7,
          "set_max": 41,
          "readonly": false,
          "mask": 65535,
          "is_hex": false,
          "is_temperature": false,
          "use_app": true,
          "display_dashboard": false,
          "display_manage": true,
          "display_info": false,
          "use_cat": true,
          "display_order": 0,
          "step": 1,
          "use_history": true,
          "use_history_output": true,
          "with_sign": false,
          "from_char_code": false,
          "notify_on_change": false,
          "is_test": false,
          "value_raw": "44",
          "value": 22.0
        },
        "temp_gas_flue_get": {
          "app_image_name": "temp_gas_flue_get",
          "reg_key": "temp_gas_flue_get",
          "reg_name": "Temperatura Fumi",
          "reg_name_app": "Temp. fumi",
          "reg_key_group": "temp_gas_flue",
          "reg_type": "GET",
          "offset": 2,
          "eeprom": false,
          "is_word": false,
          "big_endian": false,
          "formula": "#+30",
          "formula_inverse": "#-30",
          "format_string": "{0}",
          "set_min": 0,
          "set_max": 255,
          "readonly": false,
          "mask": 65535,
          "is_hex": false,
          "is_temperature": false,
          "use_app": true,
          "display_dashboard": true,
          "display_manage": false,
          "display_info": false,
          "use_cat": true,
          "display_order": 0,
          "step": 1,
          "use_history": true,
          "use_history_output": true,
          "with_sign": false,
          "from_char_code": false,
          "notify_on_change": false,
          "is_test": false,
          "value_raw": "0",
          "value": 30
        }
      }
    }
  }
}

**Comment by vincentwolsink** [comment]
I think I see the issue. I will release an update soon. For now please downgrade to the previous version.
