### ISSUE TITLE
Using with Extraflame

### ISSUE THREAD

**Issue by notkirby** [vincentwolsink/home_assistant_micronova_agua_iot#146]
Hello,

I recieved a new pellet stove (Extraflame) with a wifi module.
This one : 
https://www.lanordica-extraflame.com/fr/accessoires/module-wi-fi-etiquette-noire
https://www.lanordica-extraflame.com/sites/default/files/documenti_temp/004281071-001_man.ut_.kit_wifi_2.0_et.nera_ext.pdf

I think it's a Micronova.

Is it possible to have compatiblity with this one? I don't know if it's possible.
Thank you

**Comment by vincentwolsink** [comment]
Hi! It looks like a Micronova module indeed. If it is compatible depends on vendor API implementation. Which vendor app are you using? I will analyse it in a few weeks.

**Comment by notkirby** [comment]
Hello,
I'm using Total control 2.0 from Extraflame : https://play.google.com/store/apps/details?id=com.extraflame.smartstove&hl=fr&gl=US

Thank you for your quick answer and your help.

**Comment by 38decibel** [comment]
Hi,
I did some research.
https://totalcontrol.extraflame.it/frontend/js/lanordica-api.js
Hope this help but its not like other API pages

**Comment by vincentwolsink** [comment]
I did some sniffing on the app traffic. Although the wifi module seems to be an Micronova Agua IOT, the `Total Control 2.0` app does not use a Agua IOT API directly as backend. It seems they implemented their own API abstraction. Which makes this integration incompatible.

**Comment by notkirby** [comment]
OK thank you for your trying ! No luck for me unfortunately.

Have a nice day :)
