### ISSUE TITLE
Is an update possible?

### ISSUE THREAD

**Issue by fabienlmbt** [vincentwolsink/home_assistant_micronova_agua_iot#147]
Hi,
I just got a stove working on easy Connect. Your repository is not accessible for version 2024.5.x. Are you considering an update?
Best regards,

**Comment by vincentwolsink** [comment]
Hi @fabienlmbt. There should be no issues using the integration with HA 2024.5 (also using it myself). Why do you state it is not accessible?

**Comment by fabienlmbt** [comment]
When I search for "micronova" on HACS, I get no results. and when I try to add the deposit, I also get an error.

**Comment by vincentwolsink** [comment]
It would help if you also post the error here.

**Comment by fabienlmbt** [comment]
When I look for it, there's nothing
![image](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/147664505/56f2775d-bd4c-40dd-b370-1637fc36da9a)

**Comment by fabienlmbt** [comment]
![IMG_4920](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/147664505/6a142829-f8e4-4c7d-a91c-1249484f637d)

**Comment by vincentwolsink** [comment]
@fabienlmbt You don't have to manually install the repo into HACS because it is already part of the default set. In HACS go to Integrations, click the + button and search for Micronova.
