### ISSUE TITLE
Request: Add water pressure

### ISSUE THREAD

**Issue by Mustang1966** [vincentwolsink/home_assistant_micronova_agua_iot#148]
Is it possible to add water pressure monitoring to this integration? The Laminox Idro has a built-in boiler with central heating water.

**Comment by vincentwolsink** [comment]
Hi @Mustang1966, please post the diagnostics file from home assistant for your stove and I’ll see what I can do.

**Comment by vincentwolsink** [comment]
I see you already posted your diagnostics file before. I don’t see a register for water pressure, just an alarm in case there is something wrong.

Can you see the water pressure in you stove app?

**Comment by vincentwolsink** [comment]
Stale
