### ISSUE TITLE
Fan control

### ISSUE THREAD

**Issue by giuliovialetto** [vincentwolsink/home_assistant_micronova_agua_iot#149]
Dear all,

I recently bought a Nobis stove and am trying to improve my heating system with HomeAssistant: thank you to all who have created this integration tool!

I have the stove with a front fan and two other fans to bring hot air to other rooms. I would like to know if it is possible to manage each fan independently with this automation. For example, I would like to switch on the fan in the bedroom only in the morning. Is this possible?

Thanks in advance for any reply.

**Comment by vincentwolsink** [comment]
Hi @giuliovialetto, this integration does support multiple individual fan controls. If it works for your exact stove and situation you would need to test. You can always open an issue when things are not working as expected and I can take a look.

**Comment by giuliovialetto** [comment]
> Hi @giuliovialetto, this integration does support multiple individual fan controls. If it works for your exact stove and situation you would need to test. You can always open an issue when things are not working as expected and I can take a look.

Thank you vincent for the quick reply. I will test it in October during heating season!
