### ISSUE TITLE
Crashing again since last HA update (july 2024)

### ISSUE THREAD

**Issue by silkyclouds** [vincentwolsink/home_assistant_micronova_agua_iot#150]
Since last HA update (Juily 2024 update) : 

This error originated from a custom integration.

Logger: custom_components.aguaiot
Source: custom_components/aguaiot/__init__.py:79
integration: Micronova Agua IOT (documentation, issues)
First occurred: 1:53:04 PM (1 occurrences)
Last logged: 1:53:04 PM

Unknown Agua IOT error: Error while fetching device information

I have to delete and re-configure the intergration to get it to work again after each restart of HA. 

Once re-installed, and re-configured, it works fine.

**Comment by gzeel** [comment]
I have the same problem and see the same error messages in the logs.

**Comment by vincentwolsink** [comment]
Please enable debug logging, reload the integration and paste the output here to see if we can find the root cause.
