### ISSUE TITLE
change temp sensor

### ISSUE THREAD

**Issue by numerobis08** [vincentwolsink/home_assistant_micronova_agua_iot#151]
Hello , is it possible to change the temp sensor in the climate card to an external sensor ?

**Comment by vincentwolsink** [comment]
Hi @numerobis08, the HA climate card does not support displaying temperature of external sensors. There are community cards that have the functionality though.

**Comment by numerobis08** [comment]
> Hi @numerobis08, the HA climate card does not support displaying temperature of external sensors. There are community cards that have the functionality though.

Thanks for feedback. found some HA climate card but it changes also the set temp. any advice on which one to be used ?

**Comment by vincentwolsink** [comment]
[Simple thermostat card](https://github.com/nervetattoo/simple-thermostat) or [Better thermostat card](https://github.com/KartoffelToby/better-thermostat-ui-card) for example.
