### ISSUE TITLE
additional feature : standby ? 

### ISSUE THREAD

**Issue by silkyclouds** [vincentwolsink/home_assistant_micronova_agua_iot#152]
Hi there, 

Its all in the title, do you think we could get the "standby" mode of our stoves available to pick in the features we can pick in the climate card ? 

<img width="992" alt="image" src="https://github.com/user-attachments/assets/ad9d5908-298e-4ebc-822a-71411d06d873">

That would be great ! 

Thanks !

**Comment by vincentwolsink** [comment]
Hi, my stove does not have a standby mode. Can you explain what it exactly does and what it is used for?

**Comment by silkyclouds** [comment]
> Hi, my stove does not have a standby mode. Can you explain what it exactly does and what it is used for?

Hi Vincent,

Thank you for your quick response!

The standby mode is a feature found on Jolly Mec stoves (and possibly other brands) that allows the stove to enter a "standby" state when it reaches the target temperature.

Here’s a brief overview of how it works:

- **Standby Mode:** 
  - When enabled, the stove will turn off once it reaches the target temperature and remain off for a set number of minutes. 
  - It will automatically turn back on if the temperature drops below the target for a specified number of minutes.

  ![Standby Mode](https://github.com/user-attachments/assets/6acf0e0d-bbae-4b33-8bb9-e6310e1fc75a)

- **Regular Mode:**
  - When turned off, the stove remains active and adjusts its power to maintain the target temperature without turning on and off.

  ![Regular Mode](https://github.com/user-attachments/assets/c6dbf994-52a2-43ce-aaa6-113a03d05ff9)

Each mode has its advantages and drawbacks. In milder weather, the standby mode helps save on pellet consumption by stopping when the temperature is adequate. However, this can lead to frequent starts and stops if the room temperature drops significantly.

On the other hand, the regular mode keeps the stove continuously running, which might lead to higher temperatures when it's not very cold outside, but it is more effective when the weather turns colder.

I hope this explanation helps!

**Comment by vincentwolsink** [comment]
Thanks for your explanation. On my stove this is called eco mode 🙂 Switching this mode is actually implemented in the integration but not present on the climate entity. Unfortunately the climate entity in HA is missing such features. The only thing I can do is implement it as a “preset”. Would that work for you?

**Comment by silkyclouds** [comment]
> Thanks for your explanation. On my stove this is called eco mode 🙂 Switching this mode is actually implemented in the integration but not present on the climate entity. Unfortunately the climate entity in HA is missing such features. The only thing I can do is implement it as a “preset”. Would that work for you?

Well, as you can see, I got it working but I have to browse to my "stove programmation" dashboard to do so. the main idea would be to be able to switch it on and off directly from the climate card, which I believe need it to be a "Feature" to show up ;) 

If not possible, it is not such a great deal, I was just thinking that having this setting directly available in the card would have been beneficial to many people. 

Thanks anyway Vincent ! :)
