### ISSUE TITLE
Nobis - Fan mode meaning

### ISSUE THREAD

**Issue by giuliovialetto** [vincentwolsink/home_assistant_micronova_agua_iot#153]
Dear all, which is the meaning of the fan mode?

![Immagine 2024-09-15 135442](https://github.com/user-attachments/assets/0a95f92f-a567-4939-9cdb-1d534fec149a)

**Comment by vincentwolsink** [comment]
@giuliovialetto On the main/primary climate entity it is the power level of the stove (since the climate entity in HA does not support a seperate power setting). On additional climate entities it is the actual fan speed.

**Comment by giuliovialetto** [comment]
> @giuliovialetto On the main/primary climate entity it is the power level of the stove (since the climate entity in HA does not support a seperate power setting). On additional climate entities it is the actual fan speed.

Thank you vicent especially for the rork of this integration. May I ask you if currently this integration manage just one fan (the front one), isn't it?

I have nobis stove model with 3 fans and I am looking if in HA I am able to manage them separately: eg one manage hot air for kitchen and one for the room. I attach the screenshot of the app. These extra fans are RR and RL. May I ask your help and/or suggest me how to do?

![Screenshot_2024-09-16-19-03-07-1](https://github.com/user-attachments/assets/e63c34c9-f690-4799-b0fe-052eacad3374)

**Comment by giuliovialetto** [comment]
> @giuliovialetto This integration supports many different vents/canalizations etc. But since there is no real standard and every stove model implements it slightly different, it might be that your stove vents are not supported yet.
> 
> If you can send me the diagnostic file for the integration I will take a look.

Really thank you! Do you need just the diagnostic file of HA or also to perform an API call yo the service? If you suggest me the step to perform the call I could do it.

**Comment by vincentwolsink** [comment]
The diagnostic file from HA is sufficient 🙂

**Comment by giuliovialetto** [comment]
> The diagnostic file from HA is sufficient 🙂

Dear Vicent, here the download of the diagnostic, is it sufficient?


[config_entry-aguaiot-f7b8d8d9f2fee799f0f71834ff1ca5a9 (2).json](https://github.com/user-attachments/files/17038918/config_entry-aguaiot-f7b8d8d9f2fee799f0f71834ff1ca5a9.2.json)

**Comment by vincentwolsink** [comment]
Added support in [0.4.7](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/releases/tag/0.4.7). `Vent RR` and `Vent RL` will show up as `Canalization dx` and `Canalization sx`, don't ask me why, this is how they are exposed in the api (you can always rename them). Let me know if it works for you.

**Comment by giuliovialetto** [comment]
> Added support in [0.4.7](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/releases/tag/0.4.7). `Vent RR` and `Vent RL` will show up as `Canalization dx` and `Canalization sx`, don't ask me why, this is how they are exposed in the api (you can always rename them). Let me know if it works for you.

Really thank you vincent, it works! Could I ask you, is it necessary to connect to internet to manage the stove or do you think it is possible to manage it directly with home LAN?

**Comment by vincentwolsink** [comment]
The Agua IOT platform is fully cloud based. Unfortunately no local control possible. 🙁

**Comment by giuliovialetto** [comment]
What a pity, Nobis app seems to work also with bluetooth.

Let me say I am a newbie on integration\API, I was looking if Agua IoT with Nobis let to connect also in other way.

**Comment by giuliovialetto** [comment]
Hi @vincentwolsink do the integration let to manage also the power of the stove? I see it is possible to manage the power of each fan (vent\canalizzazione).

**Comment by vincentwolsink** [comment]
@giuliovialetto It manages the power of the stove with the “fan mode” of the main climate entity.
