### ISSUE TITLE
Mysuperior (piazetta group)

### ISSUE THREAD

**Issue by fettniamor** [vincentwolsink/home_assistant_micronova_agua_iot#158]
Hello, 

I can't connect my Superior stove (brand of the piazetta group). I see that the MySuperior application is in the list of compatible applications, but I can't connect. Is there a way to integrate my Superior Maryon stove with HA? 
Thank you for your help.

**Comment by vincentwolsink** [comment]
Hi @fettniamor. I need some more information. Is there any errors? What happens exactly when you try to configure the integration?

**Comment by fettniamor** [comment]
Hi Vincent, and thanks for your reply. 
I have a Superior stove, I go through the MySuperior application, which is a mirror application of Mypiazzetta. 
When I try to connect to the integration, I don't have "MySuperior" in the list. I tried with MyPiazetta, and I get an "unknown account" error 
I tried to create an account on the mypiazzetta application, but my stove is not recognized (logical). 
Is there a way to connect my Superior stove to this integration knowing that I have the same Agua iot module?

Thanks for your help !

**Comment by vincentwolsink** [comment]
I can take a look, but then I would need your login credentials to the account where your stove is registered (change them afterwards). Don't put them here though.

**Comment by vincentwolsink** [comment]
You can send them to temporary e-mail ziener06joduur@icloud.com

**Comment by fettniamor** [comment]
It's done. Thanks.

**Comment by vincentwolsink** [comment]
Your stove should work in version 0.4.9. Only thing is it doesn't get the name correctly (because of the way Piazetta exposes this in their proxy only) so you need to set it manually.

Please remove and reconfigure the integration after installing the newest version and choose MySuperior from the list.

**Comment by fettniamor** [comment]
It's amazing. It works perfectly! 
Thank you so much!!!
