### ISSUE TITLE
Puntofuoco Evacalor Mia pellet stove, room temperature setting

### ISSUE THREAD

**Issue by andreaciap** [vincentwolsink/home_assistant_micronova_agua_iot#160]
I have a Puntofuoco Evacalor Mia pellet stove.
This stove does not have a water hydraulic system (it only works with air) and the Min/Max heating temperature (room thermostat) must be set between 10 and 30 degrees and not between 40 and 80 degrees which is used to heat water.
How do I set these parameters?

I attach photos images of the working IOS application

![IOS_APP-EvaCalor](https://github.com/user-attachments/assets/f4b51342-210c-487f-989f-c550e0973dfd)
![HOMEASSISTANT-EvaCalor ISSUE1](https://github.com/user-attachments/assets/64c325b0-b45b-48fc-8715-de5effc64dad)

**Comment by vincentwolsink** [comment]
Hi @andreaciap, I see. Seems your stove has a unique way of exposing the controls. Can you please download the diagnostic file from HA and attach it here?

**Comment by andreaciap** [comment]
Hi Vincent.
Thanks for your interest in my problem.
I don't know how to use the disgnostic file.
I downloaded it but now I don't know this procedure.
Is there any reference on the web that I can read and study to be able to continue using the diagnostics?
Thanks again and sorry for my absence.

**Comment by vincentwolsink** [comment]
When you write a reply, please click this button and add the diagnostics file as an attachment here.

<img width="225" alt="Scherm­afbeelding 2024-10-04 om 21 41 02" src="https://github.com/user-attachments/assets/2163d956-2fbe-46d8-a68f-dd10ec3abc11">

**Comment by andreaciap** [comment]
Hi Vincent.
I'm attaching the file you requested
thanks and talk to you soon
[config_entry-aguaiot-01J8WQ1EFM9XVVDEB4VK634YVS.json](https://github.com/user-attachments/files/17268447/config_entry-aguaiot-01J8WQ1EFM9XVVDEB4VK634YVS.json)

**Comment by vincentwolsink** [comment]
Please try ![0.5.0-beta1](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/releases/tag/0.5.0-beta1)

**Comment by andreaciap** [comment]
hi vincent,
perfect everything OK, the temperature display is displayed correctly and the room temperature setup can be set as you prefer.
in case you want to set the temperature via automations/scripts what is the name of the variable to which I can set the value of the room temperature to reach?
Thanks again and have a nice day
![Screenshot (481)](https://github.com/user-attachments/assets/474cd9c6-4848-453b-aea0-a65c3ffe1d48)

**Comment by vincentwolsink** [comment]
You can set the temperature with action [climate.set_temperature](https://www.home-assistant.io/integrations/climate/#action-climateset_temperature) targeting the main climate entity.
