### ISSUE TITLE
confirm this optional component is compatible ? 

### ISSUE THREAD

**Issue by silkyclouds** [vincentwolsink/home_assistant_micronova_agua_iot#161]
Hi Vincent,

I'd like to add an extra fan to my jolly mec synthesis modular 80 to heat some extra rooms. 

https://yourserviceshop.be/fr/accessoires/3989-jolly-mec--kit-canalisation-droite-ventilateur-170m3-h.html

Can you confirm that this extra fan will be detected by your integration ? that I'll be able to start or stop the fan using the integration ? 

Thanks ! 

Raph

**Comment by vincentwolsink** [comment]
Hi Raph, unfortunatly I cannot confirm anything. I don’t own this specific stove and also don’t have any fixture data for this model. Most of the time I can make it work, but no promises 🙂

**Comment by silkyclouds** [comment]
> Hi Raph, unfortunatly I cannot confirm anything. I don’t own this specific stove and also don’t have any fixture data for this model. Most of the time I can make it work, but no promises 🙂

I will make sure to let you know everything about it ;) 

As this is something that can be used using the official micronova app, I guess it wont be too much of a challenge. we'll see ! ;)
