### ISSUE TITLE
New endpoint

### ISSUE THREAD

**Issue by cerede2000** [vincentwolsink/home_assistant_micronova_agua_iot#165]
Hi,

Please could you add this endpoint for Unical and Schuster stove :
https://unical.agua-iot.com/
Brand code 289982

Thanks :)

**Comment by cerede2000** [comment]
For test i manually modified file and it's ok 👍 
![image](https://github.com/user-attachments/assets/41206a7a-63e4-4fae-877b-6c22bc90661a)

**Comment by vincentwolsink** [comment]
Done! The vendor app is called APP-O BIOEN right?

**Comment by cerede2000** [comment]
Yes it’s correct 👍🏻
