### ISSUE TITLE
"aguaiot.sync_clock" not working for my pellet stove ‘P158 T 19.2.1 My Piazzetta’

### ISSUE THREAD

**Issue by gubas** [vincentwolsink/home_assistant_micronova_agua_iot#167]
Hello 
For my stove ‘P158 T 19.2.1 My Piazzetta’ I can't get ‘aguaiot.sync_clock’ to work.
However, all the other functions work perfectly ...

Do you have some tips ?

**Comment by gubas** [comment]
`Enregistreur: custom_components.aguaiot.climate
Source: custom_components/aguaiot/climate.py:324
intégration: Micronova Agua IOT ([documentation](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/), [problèmes](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/issues))
S'est produit pour la première fois: 26 octobre 2024 à 19:00:00 (7 occurrences)
Dernier enregistrement: 13:27:48

Failed to set value, error: Value must be between 15 and 50: 2024`

**Comment by vincentwolsink** [comment]
Should be fixed in [0.5.2](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/releases/tag/0.5.2) :)

**Comment by gubas** [comment]
Perfect ! It's work ! Thanks !
