### ISSUE TITLE
stove UNICA NOBIS FIRE not climate ma number

### ISSUE THREAD

**Issue by merlino1975** [vincentwolsink/home_assistant_micronova_agua_iot#169]
hi, I've a questions..
 Is possible to have a number.stufa_salotto_vent_rear?  now I have only climate:stufa_salotto_vent_rear but i cannot use to set in node red fan speed. in nodered..so if there are both one and the other it would be better
thanks

**Comment by vincentwolsink** [comment]
Hi! You can call the action [climate.set_fan_mode](https://www.home-assistant.io/integrations/climate#action-climateset_fan_mode) from Node-RED. As destination use your climate.stufa_salotto_vent_rear

**Comment by merlino1975** [comment]
okey...just do it (i don't know what.. but I deleted and remaked the node and work fine)...now another question for you...please..
do you have a list of all the states and all the attributes of all the entities of the unique micronova nobis? Because I often can't figure out how to configure the nodes. for example: if I go into the entity's history, if you select the wood reserve it tells me the state is "ok" (I imagine it means that the wood is sufficient) but when it enters the wood reserve, how does the status change? So I would like a list for all the other entities too if possible thanks

**Comment by vincentwolsink** [comment]
I added them in  [0.6.0](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/releases/tag/0.6.0)

**Comment by merlino1975** [comment]
thanks for the replyI'm sorry to bother you for such simple things, unfortunately I'm not a programmer, and I'm not even that intelligent, for me the world of home automation is a new, intriguing and interesting world. unfortunately I lack the basics and often ask stupid questions. like for example the next one I'll make for you:I have searched and searched in every way to find a way to find by myself all the states and attribute names that an entity can have.For example also of all the entities of your work. I still don't understand how to use many of them because I don't know what states or attributes they can take on. Is there a way to figure this out? or simply where should I look for the necessary documentation to discover this data?Thank you again for your infinite patience with meInviato dal mio Galaxy
-------- Messaggio originale --------Da: Vincent Wolsink ***@***.***> Data: 27/11/24  07:48  (GMT+01:00) A: vincentwolsink/home_assistant_micronova_agua_iot ***@***.***> Cc: merlino1975 ***@***.***>, Author ***@***.***> Oggetto: Re: [vincentwolsink/home_assistant_micronova_agua_iot] stove UNICA
  NOBIS FIRE not climate ma number (Issue #169) 
Btw, wood reserve is a binary sensor so you can just use on or off

**Comment by merlino1975** [comment]
forgiveness, an observation and a request for explanation. If I may abuse your patience.I have made a routine that if I open the pellet door (the stove gives an AL16 alarm and gives me a minute to load the pellets otherwise the stove turns off) Alexa makes me count down e.g. there are 60 seconds left to load the pellets, or something like that.But when I open the door it doesn't start the routine immediately but after about 10 seconds or more. I don't understand if it's a problem with the entity, if it's a problem with my home assistant server, if I'm doing something wrong in writing the routine. or if it's alexa that's slow.What do you think about itInviato dal mio Galaxy
-------- Messaggio originale --------Da: Vincent Wolsink ***@***.***> Data: 27/11/24  07:48  (GMT+01:00) A: vincentwolsink/home_assistant_micronova_agua_iot ***@***.***> Cc: merlino1975 ***@***.***>, Author ***@***.***> Oggetto: Re: [vincentwolsink/home_assistant_micronova_agua_iot] stove UNICA
  NOBIS FIRE not climate ma number (Issue #169) 
Btw, wood reserve is a binary sensor so you can just use on or off

**Comment by vincentwolsink** [comment]
> I have searched and searched in every way to find a way to find by myself all the states and attribute names that an entity can have.For example also of all the entities of your work. I still don't understand how to use many of them because I don't know what states or attributes they can take on. Is there a way to figure this out?

Usually you can find this in documentation. Since the states for this integration are dynamic and differ per stove I added them to the extra attributes for you, where applicable.

<img width="551" alt="Scherm­afbeelding 2024-11-27 om 10 04 39" src="https://github.com/user-attachments/assets/f40419da-fb82-489e-aa7f-dad80afaa5e6">

> But when I open the door it doesn't start the routine immediately but after about 10 seconds or more. I don't understand if it's a problem with the entity, if it's a problem with my home assistant server, if I'm doing something wrong in writing the routine.

This integration (just like a majority of the integrations) relies on cloud polling for getting updates. This polling happens every 5 min. Which means worst case there is a 5 min delay between you opening the door and AL16 alarm happening. There is no way to make this faster since this will overload the cloud endpoints.
