### ISSUE TITLE
check the front fan value

### ISSUE THREAD

**Issue by merlino1975** [vincentwolsink/home_assistant_micronova_agua_iot#180]
I would like to understand how to check (I use nodered) with a "wait until" node whether the front fan (Real Vent Front living room stove) is a PS mode but it only gives me the values ​​from OFF to 7. Can this be corrected or is it a value which can only be set with the climate.stufa_salotto_vent_front entity? in this case I'm in trouble because I can't make it work with the "wait until" control

**Comment by vincentwolsink** [comment]
I added the possible values for the sensors to the custom attributes for you to check. If it is not there, it is not possible.
