### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by manueltorpi** [vincentwolsink/home_assistant_micronova_agua_iot#181]
Dear Vincent,

I'm trying to install your integration for controlling my Nobis stove, but in the device views I don't have any controls or sensors. Here the screen shot of the home assistant page. 
![Screenshot_20241208_092600_Home Assistant](https://github.com/user-attachments/assets/3f29360b-389a-48da-8f86-def91da23926)

After the installation from HACS, home assistant requires the reboot, but no control flow for the configuration started. 

Am I doing something wrong? Do you have any suggestions?

Thank you so much for your support

**Comment by vincentwolsink** [comment]
Hi! After installing the integration via HACS, did you add it?

Settings > Devices & Services > Add Integration (button in bottom right corner) > Select Micronova Agua IOT from the list and enter the needed configuation.

**Comment by manueltorpi** [comment]
Done!
Now it works fine. Many thanks.
