### ISSUE TITLE
set the manual operation of the stove

### ISSUE THREAD

**Issue by merlino1975** [vincentwolsink/home_assistant_micronova_agua_iot#183]
another problem, but I don't know if I set something wrong or there is a bug.
I set the remote control to manual, to do this you need to set the thermostat in the remote control to the maximum, i.e. raise all possible degrees after which the word MAN appears on the display which means manual.
In the dashboard the temperature box is not set manually as it should be... but 41 degrees, why? could they conflict?

**Comment by vincentwolsink** [comment]
Home Assistant only supports numbers for the temperature (which makes sense). 41 degrees is indeed `MAN`.
