### ISSUE TITLE
Laminox Boiler Temperature

### ISSUE THREAD

**Issue by Mustang1966** [vincentwolsink/home_assistant_micronova_agua_iot#20]
Is it possible to add the Boiler Temperature for the Lamnox Pellet CV? It's available in the Laminox app, but not in Home Assistant.

**Comment by vincentwolsink** [comment]
Hi @Mustang1966, please enable debug logging for this integration in HA for a couple minutes and send me the log. I can then check if the boiler temperature is available.

**Comment by Mustang1966** [comment]
Hallo Vincent,

Hierbij de logging van de Laminox.

Groet Alle

Op vr 4 aug 2023 om 18:43 schreef Vincent Wolsink ***@***.***

**Comment by vincentwolsink** [comment]
Hoi @Mustang1966, de logging is niet aanwezig bij je laatste bericht.

**Comment by Mustang1966** [comment]
[home-assistant_aguaiot_2023-08-11T21-15-13.561Z.log](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/files/12325213/home-assistant_aguaiot_2023-08-11T21-15-13.561Z.log)

**Comment by vincentwolsink** [comment]
I could find a parameter to set boiler temperature (which is currently set to 66 degrees celsius), but not with the current temperature. Could you maybe install the latest version of this integration. Download diagnostics via the button "Diagnostiek downloaden" and also write down the boiler temperature displayed by the Lamnox app?

**Comment by Mustang1966** [comment]
Temperature 60, sometimes 61 during the logging.. The current boiler temperature is set to 55 dregees.

[home-assistant_aguaiot_2023-08-12T07-20-49.199Z.log](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/files/12326846/home-assistant_aguaiot_2023-08-12T07-20-49.199Z.log)

**Comment by Mustang1966** [comment]
Updated to 1.6 and downloaded the diagnostics, this value corresponds with the current temperature. 
        "temp_water_get": {
            "reg_type": "GET",
            "offset": 3,
            "formula": "#",
            "formula_inverse": "#",
            "format_string": "{0}\u00b0C",
            "set_min": 0,
            "set_max": 255,
            "mask": 65535,
            "raw_value": 72,
            "calculated_value": 72,
            "formatted_value": "72\u00b0C"

**Comment by vincentwolsink** [comment]
That value is actually implemented, but only picked when air temperature is not available. It seems for your stove it exposes both (although air temperature is 0). Can you maybe make a screenshot of the app for me to see which information is available there?

**Comment by Mustang1966** [comment]
![Screenshot_20230813-155812](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/43118018/99133080-c016-42b5-a3a5-6b2ecfdb73a1)
![Screenshot_20230813-155834](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/43118018/9a69e5a9-ecc1-4584-b7d3-b24d9bd4ca05)

**Comment by vincentwolsink** [comment]
Does your stove also do air heating? Or just water?

**Comment by Mustang1966** [comment]
Hello Vincent, it's only water.

**Comment by vincentwolsink** [comment]
Hi @Mustang1966, please try [v0.1.7-beta1](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/releases/tag/v0.1.7-beta1)

**Comment by Mustang1966** [comment]
It works like a charme.. Thank you for this!
