### ISSUE TITLE
Additional settings for mypiazetta

### ISSUE THREAD

**Issue by ethanmes** [vincentwolsink/home_assistant_micronova_agua_iot#27]
Hello,

Is it possible to access these types of settings (energy saving, night mode,...) on the stove like this user on jeedom with the same plugin?

Thanks in advance

Ethan.

**Comment by vincentwolsink** [comment]
Hi, can you add a link to what you are referring to?

**Comment by ethanmes** [comment]
Sorry, I've completely forgotten the link (in french)

https://community.jeedom.com/t/pilotage-de-mypiazzetta-avec-le-plugin-poele-agua-iot/91413

**Comment by vincentwolsink** [comment]
If you attach the HA diagnostics file for your stove here and tell me which settings you would like to adjust specifically, I can take a look.

**Comment by ethanmes** [comment]
Hello,

I want to adjust the energy saving (start and stop) and the natural mode.

Here the file : [config_entry-aguaiot-b7d56dc5345da7541780671c914a2e6c.json.txt](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/files/12406170/config_entry-aguaiot-b7d56dc5345da7541780671c914a2e6c.json.txt)

I deleted some information because I didn't know if it was linked to my piazetta account.

Thanks a lot.

**Comment by ethanmes** [comment]
Hello,

Thanks a lot. It works for the energy saving start and stop.

<img width="694" alt="Capture d’écran 2023-08-24 à 22 36 27" src="https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/79789733/4e18e76b-355e-48e5-9b9e-a5f00a6957ef">

For natural mode, I have the switch, the state is the right one (if I enable/disable natural mode in the mypiazetta app, it updates in HA) but I can't switch on/off the mode in HA, I get this error:

Echec de l'appel du service switch/turn_on. name 'boolean' is not defined

**Comment by ethanmes** [comment]
And this error if i disable the natural mode :

Echec de l'appel du service switch/turn_off. name 'boolean' is not defined

**Comment by vincentwolsink** [comment]
Should be fixed in [v0.1.8-beta2](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/releases/tag/v0.1.8-beta2)

**Comment by ethanmes** [comment]
I have now this error : 

Échec de l'appel du service switch/turn_on. Blocking calls must be done in the executor or a separate thread; Use `await hass.async_add_executor_job()`; at custom_components/aguaiot/switch.py, line 76: setattr(self._device, self.entity_description.key, True)

**Comment by vincentwolsink** [comment]
I will take a closer look later. Since my stove doesn’t have the features it is a bit hard to test. But i will fix it.

**Comment by ethanmes** [comment]
Ok no problem, thank you ! :)

**Comment by vincentwolsink** [comment]
Fix: [v0.1.8-beta3](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/releases/tag/v0.1.8-beta3)

**Comment by ethanmes** [comment]
Thank you very much, everything works!
