### ISSUE TITLE
Can't connect my Piazetta P939

### ISSUE THREAD

**Issue by cabadietech** [vincentwolsink/home_assistant_micronova_agua_iot#47]
Hello and first of all thank you for your work. 
I recently moved from Jeedom to home assistant but so far I can't connect to my piazetta P939 within HA. The jeedom plugin also based on py-agua-iot is working perfectly so I used the exact same parameters to configure it on HA but I still have a connection error message.
here are the value I use 
url : https://piazzetta-iot.app2cloud.it/api/bridge/endpoint/
login url : https://piazzetta-iot.app2cloud.it/api/bridge/endpoint/
customer code : 458632
login & password that I use on the mobile app
Version 1.9.0
Brand ID : 1 

I tried the stable plugin 1.8 and de 2.0 beta but not better.
I'll appreciate any help.
Thanks !
Christophe

**Comment by jipem01** [comment]
Try without setting login URL.

**Comment by cabadietech** [comment]
> Try without setting login URL.

Thank you but still get the connection error.
![image](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/5444733/3729d3e3-dbb5-4f26-b1b3-016a1b41a1b6)

**Comment by jipem01** [comment]
From py-agua-iot readme,Api URL : https://piazzetta.agua-iot.com/Login URL : https://piazzetta-iot.app2cloud.it/api/bridge/endpoint/It seams that you use login URL instead API URL.

**Comment by cabadietech** [comment]
> From py-agua-iot readme,Api URL : https://piazzetta.agua-iot.com/Login URL : https://piazzetta-iot.app2cloud.it/api/bridge/endpoint/It seams that you use login URL instead API URL.

You are a life savior ! It works ! Thank you so much !

**Comment by cabadietech** [comment]
The issue was between the chair and the keyboard !
