### ISSUE TITLE
Laminox Climate Entity Missing

### ISSUE THREAD

**Issue by Mustang1966** [vincentwolsink/home_assistant_micronova_agua_iot#48]
After upgading to the latest version, the climate entity is missing for the Laminox Idro.

[config_entry-aguaiot-b4b7eeb4488df45083795da860e9fc62.json.txt](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/files/12775265/config_entry-aguaiot-b4b7eeb4488df45083795da860e9fc62.json.txt)

[home-assistant_2023-09-30T14-20-46.319Z.log](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/files/12774886/home-assistant_2023-09-30T14-20-46.319Z.log)

**Comment by jipem01** [comment]
Hi Mustang could you attach integratio  diagnosis and also HA logs?

**Comment by Mustang1966** [comment]
Added logs

> Hi Mustang could you attach integratio  diagnosis and also HA logs?

**Comment by jipem01** [comment]
Could your check aguiot diagnosis file? It's the same content than HA log, but shouldn't.Go to Micronova integration, select your stove device and then "diagnostic" (sorry I don't have the exact path name in english).

**Comment by Mustang1966** [comment]
updated!


> Could your check aguiot diagnosis file? It's the same content than HA log, but shouldn't.Go to Micronova integration, select your stove device and then "diagnostic" (sorry I don't have the exact path name in english).
