### ISSUE TITLE
Piazetta pelletstove Natural mode?

### ISSUE THREAD

**Issue by bcornelissen1** [vincentwolsink/home_assistant_micronova_agua_iot#63]
Hi,

Not really willing to report a issue, but more a question. In version 0.1.8 i got the Natural mode functionality which i really liked, i did not need to use the MyPiazetta app to turn off the fan anymore. 

Since 0.2.0+ versions i am missing this mode again. Now having only 4 available sensors, where before i had 6. Is this something that can be added back in newer versions?

Thanks a lot for your work!

Kr,
Bart

**Comment by vincentwolsink** [comment]
Hi Bart, I did not remove that functionality so this must be a regression. Can you please share your diagnostics file?

**Comment by bcornelissen1** [comment]
Many thanks, it's back now !
