### ISSUE TITLE
Micronova Agua iot (jolly mec)

### ISSUE THREAD

**Issue by Nico72120** [vincentwolsink/home_assistant_micronova_agua_iot#66]
Bonjour, 

Je ne pense pas que cela vienne de Home assistant et de la mise a jour car l'application Jollymec wifi ne fonctionne plus depuis vendredi 14/10 18:26 comme Home assistant. Est-ce pareil pour vous ?

J'ai ça :
Cette erreur provient d'une intégration personnalisée

Logger: custom_components.aguaiot.aguaiot
Source: custom_components/aguaiot/aguaiot.py:161
Integration: Micronova Agua IOT (documentation, issues)
First occurred: 20:45:50 (1 occurrences)
Last logged: 20:45:50

Failed to register app id. Code: 502, Response: <html> <head><title>502 Bad Gateway</title></head> <body> <center><h1>502 Bad Gateway</h1></center> <hr><center>nginx</center> </body> </html>

Merci pour votre aide,

**Comment by vincentwolsink** [comment]
Please put some effort in to write your question in English. But looking at the error message it looks like Jollymec had backend problems.

**Comment by Nico72120** [comment]
Excuse for my english. You can delete my issue because it's ok this evening... it's Jollymec api which is fault last day. This evening it's works.
