### ISSUE TITLE
Nobis stove alarm not displayed

### ISSUE THREAD

**Issue by jipem01** [vincentwolsink/home_assistant_micronova_agua_iot#7]
Having my nobis stove navel and nobis-fi app display AL-03, but HA heating controller widget displaying "heating, inactive".
Some error not handled / prioritized somewher between py-agua-iot lib and the plugin. I'll provide additional details as soon as possible.

Nobis A10V stove, AL03 is out of pellet.

**Comment by vincentwolsink** [comment]
[v0.2.0-beta1](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/releases/tag/v0.2.0-beta1) might fix this. I also moved the alarms to a separate sensor.
