### ISSUE TITLE
piazzetta P958 T 16.0

### ISSUE THREAD

**Issue by petitbajou215177** [vincentwolsink/home_assistant_micronova_agua_iot#73]
Hello everyone,
I just installed the agua iot integration and my Piazzetta P958 device appears in Home Assistant. However, I have a problem with the "climate" part.
The current temperature does not correspond to reality:
![image](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/72158790/fc995b0a-b0c3-4e71-9c1b-495a6dbf5fe7)
Can you help me?
Furthermore, I do not have an entity that goes up for ventilation (from 1 to 3), only power (from 1 to 4).
For those who have a piazzetta how many entities do you receive?
![image](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/72158790/6f779227-5d74-46dc-8bc3-fe2ee715d90f)
Thanks in advance

**Comment by vincentwolsink** [comment]
Hi @petitbajou215177, can you please attach the diagnostics file for the integration? The separate ventilation entity might not be implemented. What do you use it for?

**Comment by petitbajou215177** [comment]
diagnostics file:
[config_entry-aguaiot-77b5e9f337b5b7b1703581f0989f5b80.json(1).txt](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/files/13041209/config_entry-aguaiot-77b5e9f337b5b7b1703581f0989f5b80.json.1.txt)
For the ventilation it's "multifluco"
![image](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/72158790/ea101160-4964-42d7-b74c-eb6d10fc6b20)
thanks

**Comment by petitbajou215177** [comment]
Hi Vincent,
the v0.2.5.beta1 version works, the current temperature is good. 
![image](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/72158790/5c5b8810-81a2-4213-acde-99c60c14013e)
For ventilation it is also ok.
![image](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/72158790/da1f647f-b184-414d-aad9-d78e33205208)
Thank you very much for your dedication
