### ISSUE TITLE
Fan speeds

### ISSUE THREAD

**Issue by PaulStoop86** [vincentwolsink/home_assistant_micronova_agua_iot#79]
Hello Vincent, 

For starters: thank you very much for your integration, i'm pretty new to HA and your integrations workes like a charm, controlling my Nordic Fire SIENNA pelletstove like it should. 

I was wondering if you ever run into a palletstove with two controllable fans? The fans are used to disperse the heat into two separate ducts. I'am using one fan to direct air into the livingroom, the other fan to direct heat to the hallway/second floor. It would be great if i could combine external temperature sensors with the individual fan settings to direct the heat to the rooms in which it is needed most. But at his moment, the loaded entities dont show the fans. (although your latest version seems to mention a "fan setting")

The "official" nordic fire app shows these fans are "ducted 1 and ducted 2) And there are 6 settings for each fan: 1, 2, 3, 4, 5 and A (automatic)
![Afbeelding van WhatsApp op 2023-10-19 om 20 28 11_7145854c](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/136022588/be2422de-4895-4eb8-bb88-d746a32d54a4)

I tried searching the API documentation to see if there is support for this feature, but i think i lack the know-how at this moment to determine this myself. 

If there is no support for this feature you can offcourse close this isssue, 

Thank you for your reply, 

Best regards,

**Comment by PaulStoop86** [comment]
Just found a closed issue with a similar question (sorry, pretty new to github as well). This questions seems to be about a different brand stove. 

For extra info below the diagnostics file in which ( i think) the canalization 1&2 are visible 

[config_entry-aguaiot-319f7814d4f079ef6deacd212a5908f3.json.txt](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/files/13046567/config_entry-aguaiot-319f7814d4f079ef6deacd212a5908f3.json.txt)

**Comment by vincentwolsink** [comment]
Hi @PaulStoop86, these are already implemented for other brands. But unfortunately there is very little standards in the API, even between stoves from the same brand.

I can implement them for your stove too. I will take a look this evening 🙂

**Comment by inode-** [comment]
Same question for Piazzetta 183. It would be possible to add the "vent_front" as fan? 

I can provide you the credentials without problems or sniff/intercept the HTTP traffic for you.

[config_entry-aguaiot-4f60b5836f2bd1a9e0b632cffaba20e2.json.txt](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/files/13055504/config_entry-aguaiot-4f60b5836f2bd1a9e0b632cffaba20e2.json.txt)

Thank you

**Comment by vincentwolsink** [comment]
@inode- Sure. I will probably implement it today.

**Comment by vincentwolsink** [comment]
Please try [v0.2.5-beta3](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/releases/tag/v0.2.5-beta3)

**Comment by PaulStoop86** [comment]
Wow, thanks for the quick implementation. I now have a canalization_2 in HA, which works 
(the option "off" is not in the official app/on the remote. App and remote only shows 1 to 5 and "A". Funny thing is that setting it to "off" in your integration does turn of the fan and update remote to "OFF", which is normally no option. Not sure if the stove can handle two fans turned off:)  

However: Canalization_1 is not visible. 
Might be result of the following HA log entry: 

_Platform aguaiot does not generate unique IDs. ID A28C3EC1-BF8F-4A37-A4BC-27C68CA0E683_canalization_2_set already exists - ignoring climate.woonkamer_canalization_2_

Again: many thanks for your effort!

**Comment by vincentwolsink** [comment]
v0.2.5-beta4 should fix that :)

**Comment by PaulStoop86** [comment]
Yes! Thanks.  Two fans visible, will test tomorrow, but i think this closes my issue:)

**Comment by PaulStoop86** [comment]
Tested today. Everything works perfect:) Ready for automations and a custom card. Thanks for the implementation, the quick responses and actions. 

Have a nice weekend!

**Comment by inode-** [comment]
I was finishing the setup after a while, but the fan created seems to implement someting in the wrong way. All the data should be on the "Mode" directly, or I'm wrong?

![image](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/4608466/5db2ed39-79ae-400c-8e04-880b77afe366)

![image](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/4608466/97d3d936-e957-40a4-84db-899906690993)
