### ISSUE TITLE
Missing error/alarm entity

### ISSUE THREAD

**Issue by inode-** [vincentwolsink/home_assistant_micronova_agua_iot#81]
Not totally sure, but it seems that the alarm entity is missing on Piazzetta P163. I'm doing something wrong?

Just tried to reconfigure it from zero, but doesn't seems to have the old attribute or the new entity.

![image](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/4608466/bc61cbde-5de3-48c2-9f46-01c86522be4f)

![image](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/4608466/c65d2fb7-f49a-446e-8782-3b988acc05f7)

[config_entry-aguaiot-4f60b5836f2bd1a9e0b632cffaba20e2.json.txt](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/files/13055675/config_entry-aguaiot-4f60b5836f2bd1a9e0b632cffaba20e2.json.txt)

Thank you

**Comment by vincentwolsink** [comment]
This is because the registry for the alarms is not enabled. Maybe the enable is working differently for these stoves and only enables once an alarm is happening. I will check it out.

Can you maybe force an alarm to happen and supply the diagnostics file?

**Comment by inode-** [comment]
Error E9 generates ;)

[config_entry-aguaiot-4f60b5836f2bd1a9e0b632cffaba20e2.json (1).txt](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/files/13056108/config_entry-aguaiot-4f60b5836f2bd1a9e0b632cffaba20e2.json.1.txt)

![image](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/4608466/3ca4bc43-7243-4c53-b400-c9e66300ad84)

**Comment by vincentwolsink** [comment]
Please try [v0.2.5-beta3](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/releases/tag/v0.2.5-beta3)

**Comment by inode-** [comment]
Thank you! Any way to offer you a beer?

**Comment by vincentwolsink** [comment]
Happy to help. Don't expect anything in return. But if you want to 🍺 [Buy me a beer](https://www.buymeacoffee.com/vincentwolsink) I will never say no 😄
