### ISSUE TITLE
enable error codes back ?

### ISSUE THREAD

**Issue by silkyclouds** [vincentwolsink/home_assistant_micronova_agua_iot#86]
Hi Vincent, 

We already discussed this topic when you introduced the new alarm entity, but in my specific scenario, I took the time to analyse each alarm code of my stove. therefore , I spent time checking each numeric value the stove controller was reporting during this or that phase. 

Thanks to this, I was able to translate the code status codes to human readable statuses : 

````
    readable_device_status:
      value_template: >-
        {% set t = states('sensor.device_status')|int(0) %}
        {% set values =
            ['Insert éteint', 'Démarrage', 'Préchauffe',
             'Chargement pellets allumage', 'Allumage bougie', 'Allumage initial',
             'Finallisation allumage', 'Chauffage en cours', 'Demande extinction',
             'Nettoyage final', 'Attente de Standby', 'Standby',
             'Alerte: Plus de pellet', 'Alerte: Nettoyer brasier'] %}
        {{ values[t] }}
    readable_real_power:
      value_template: >-
        {% set t = states('sensor.real_power')|int(1) %}
        {% set values =
            ['Eco', 'Eco', 'Low',
             'Medium', 'High', 'Giga',
             'Ultra'] %}
        {{ values[t] }}
````

Due to this, it would be really nice for me to get these codes back in your integration. As it would display the real statuses of my stove again, and would make my automations (I let alexa tell me when I'm out of pellets, when the final cleaning is done (so I can clean the stove...) work again. 

Is this something you could re-enable ? Because the best I can get now is "no alarm", which is not really helpful in this scenario. 

Thanks for your consideration ;)

**Comment by vincentwolsink** [comment]
It is already back, see my [answer](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/issues/49#issuecomment-1757318823) in your previous issue.

**Comment by vincentwolsink** [comment]
If you need any help please reopen this issue 🙂
