### ISSUE TITLE
Pellets depleted not displayed as status/alarm

### ISSUE THREAD

**Issue by Donder24** [vincentwolsink/home_assistant_micronova_agua_iot#87]
Hi,

just tested the " pellets depleted " because my stove ran out off pellets, but the alarm isn't displayed.
State says : "Working"
Alarm says: "no AL" 

Does anybody know where I can find this? 

[config_entry-aguaiot-ff6449b5b8ca4a3f878103b86ee1f0d7-1.json](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/files/13078209/config_entry-aguaiot-ff6449b5b8ca4a3f878103b86ee1f0d7-1.json)

**Comment by vincentwolsink** [comment]
It this diagnostics file from the moment the pellets were depleted? It seems that pellets depleted is not implemented as an alarm. Does the stove app show an alarm? I do see a register that might be the one we need, but that also seems to indicate that the pellets are ok.

**Comment by Donder24** [comment]
Yes (this is indeed when the alarm was active) and yes the app shows this
alarm also.

I have another diagnostics file also from this moment.

Op ma 23 okt. 2023 21:17 schreef Vincent Wolsink ***@***.***>:

**Comment by vincentwolsink** [comment]
Can you also send a debug file when the pellet container is full? And this alarm is triggered before the container is completely empty?

**Comment by Donder24** [comment]
Sure, yes there´s a sensor at a certain height and when it doesn´t detect pellets anymore, you´ve got 30min to refill.
Else the stove stops working.

**Comment by vincentwolsink** [comment]
Please try [v0.2.6-beta1](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/releases/tag/v0.2.6-beta1)

**Comment by Donder24** [comment]
I´ve updated the integration but it might take a few days before the alarm becomes active again since I just poured in a whole bag...
Keep you posted!

**Comment by vincentwolsink** [comment]
You should already see the new sensor. Let me know if it works like expected when the stove is empty :)

**Comment by Donder24** [comment]
You´re the best! 🥇 

Works like expected! Great job! If you´re dutch speaking, the result: 
![Screenshot_20231026_201612_One UI Home](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/83492249/094f4dc9-cea7-4a20-a695-550418c620cd)
