### ISSUE TITLE
Connection to Agua IOT API not possible - stove NOBIS-FI

### ISSUE THREAD

**Issue by merlino1975** [vincentwolsink/home_assistant_micronova_agua_iot#89]
Hi, I tried to install and set up micronova agua iot but it gives me an error.
what to say?
home assistant and hacs are installed in a docker container on synology NAS
![Screenshot 2023-10-28 23 50 29](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/34696169/de8dfcb3-4e8c-4d9a-910b-efba706ab0e3)

and i think this may be the message recordered in the log

![Screenshot 2023-10-29 00 10 40](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/34696169/d1a7f8ff-8c3c-45fa-b0e8-c76b860c1486)

thanks, I hope you can help me...I hope there is a solution...

**Comment by jipem01** [comment]
First input, place the URL:https://nobis.agua-iot.comSecond input (separate login), leave it empty. Only few brands use it.No link to your bug, but what is your stove model?
-------- Message d'origine --------De : merlino1975 ***@***.***> Date : 28/10/2023  23:57  (GMT+01:00) À : vincentwolsink/home_assistant_micronova_agua_iot ***@***.***> Cc : Subscribed ***@***.***> Objet : [vincentwolsink/home_assistant_micronova_agua_iot] Connection to Agua IOT API not possible - stove NOBIS-FI (Issue #89) 
Hi, I tried to install and set up micronova agua iot but it gives me an error.
what to say?

thanks, I hope you can help me...I hope there is a solution...
