### ISSUE TITLE
Climate entity not working

### ISSUE THREAD

**Issue by thechris964** [vincentwolsink/home_assistant_micronova_agua_iot#90]
Hello,

since the update to the version, the climate entity no longer works. (Error: no longer available)

My stove: MCZ ST.TEIA COMFORT AIR 10 S1

Before, everything worked wonderfully. Is there a solution?

**Comment by vincentwolsink** [comment]
Hi, please provide the relevant errors from the home assistant log

**Comment by thechris964** [comment]
Hi,

there you go.

I will now downgrade to version 0.2.4. so that my automations work again.

Diagnostic´s also attached.
Ha-Log File: (also attached as .txt)
[Ha-LOG.txt](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/files/13198770/Ha-LOG.txt)


**Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:359
Integration: Klima (documentation, issues)
[config_entry-aguaiot-8b79240de84a990baee06e63fb2a8959.json.txt](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/files/13198771/config_entry-aguaiot-8b79240de84a990baee06e63fb2a8959.json.txt)

First occurred: 18:30:56 (1 occurrences)
Last logged: 18:30:56

Error while setting up aguaiot platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/aguaiot/climate.py", line 51, in async_setup_entry
    for fan_found in [
                     ^
  File "/config/custom_components/aguaiot/climate.py", line 55, in <listcomp>
    if m and device.get_register_enabled(m[0])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/aguaiot/aguaiot.py", line 560, in get_register_enabled
    raise AguaIOTError(f"Not a register of type ENABLE: {key}")
custom_components.aguaiot.aguaiot.AguaIOTError: Not a register of type ENABLE: canalization_1_set
**

**Comment by vincentwolsink** [comment]
Should be fixed in v0.2.7
