### ISSUE TITLE
Nordicfire 1.0 app

### ISSUE THREAD

**Issue by hanzpeeters** [vincentwolsink/home_assistant_micronova_agua_iot#91]
Hello, I'm using the older 1.0 app with a Nordic fire ILVAR pellet stove. Is there a possibility to connect it with HA? I tried to install the repo in HA, but can't connect with the stove. Then i reached out to Nordic fire in the Netherlands and the told me my "older" stove has to use the 1.0 app.

**Comment by vincentwolsink** [comment]
It is very likely that the older Nordic fire app is not built on top of Agua IOT. In that case you will not be able to connect. But I can double check. Please post a link to the app (in the app store) you are using.

**Comment by hanzpeeters** [comment]
Thank you very much for your reply. The old app is here [https://play.google.com/store/apps/details?id=it.omniaweb.efesto.nordicfire&hl=nl&gl=US](url)

**Comment by vincentwolsink** [comment]
The old app doesn't send me an e-mail to activate my account. But looking at the registration process it is highly likely it is using an other system than Agua IOT and unfortunatly won't be compatible with this integration.
