### ISSUE TITLE
Failed to login

### ISSUE THREAD

**Issue by SimmacoMe** [vincentwolsink/home_assistant_micronova_agua_iot#94]
Hi, I installed the Micronova addon, when I try to connect it gives me a credentials error. but they are undoubtedly right
<img width="385" alt="Screenshot 2023-11-02 alle 18 46 02" src="https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/32878947/32119924-9542-445f-be9f-c909139a2bc3">

**Comment by vincentwolsink** [comment]
Hi, can you please provide the relevant error log entry from the Home Assistant logs?

**Comment by SimmacoMe** [comment]
![Uploading Screenshot 2023-11-03 alle 16.23.24.png…]()

**Comment by SimmacoMe** [comment]
<img width="681" alt="Screenshot 2023-11-03 alle 16 23 24" src="https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/32878947/8b5f7c77-189f-46d3-8f7b-a477bc5a9342">

**Comment by vincentwolsink** [comment]
The response from the API is `LOGIN_USER_NOT_FOUND`. Are you really sure your credentials are correct? Maybe your stove uses an (older) version app that is not based on Agua IOT?

**Comment by SimmacoMe** [comment]
The credentials I use to connect to the stove are certainly these, the site after connecting is cloudwinet.it. the stove is new just bought and installed. How can I check to see if he uses Agua IOT? the motherboard is certainly micronova mod 0047 evo

**Comment by vincentwolsink** [comment]
WiNET IOT is unfortunately a different product/platform than Agua IOT and cannot be used with this integration.
