### ISSUE TITLE
Plugin not found in HACS

### ISSUE THREAD

**Issue by jtredez** [vincentwolsink/home_assistant_micronova_agua_iot#95]
Hello,

This is my Home Assistant configuration:
Core 2023.11.1
Supervisor 2023.10.1
Operating System 11.1
Interface utilisateur 20231030.1
On a raspberry pi 3.

I have installed Home Assistant Community Add-ons but I can't found the Micronova agua iot inside the store.

**Comment by jipem01** [comment]
Did you restarted HA?

**Comment by jtzmyfox** [comment]
Yes, this is the list of Community Add-ons I have
![image](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/9868209/e11b434d-e8da-4242-9578-aa03864b4c3e)

**Comment by vincentwolsink** [comment]
Hi @jtzmyfox. That is the Home Assistant Add-ons store. Your need to install [HACS](https://hacs.xyz/) and then look for the HACS button in the sidebar.

**Comment by jtredez** [comment]
Thank you it's working, I perform the wget.... and restart HA, but thought it was enough.
I forgot to install HACS from the Integration device.
