### ISSUE TITLE
Second duct controls missing

### ISSUE THREAD

**Issue by merlino1975** [vincentwolsink/home_assistant_micronova_agua_iot#98]
hi
we've a problem (huston copy)

I installed the API for the nobis fire stove, my stove has 2 ducts, but as an entity in Home Assistant I only see 1 duct, the controls for the second duct are missing, then there would also be the room temperature sensors for both the first canalization and the second canalization.

integration is required

thanks!!

**Comment by vincentwolsink** [comment]
Hi, please provide a screenshot of the available entities and attach your diagnostic file.

**Comment by merlino1975** [comment]
the stove is  unica nobis fire

**Comment by merlino1975** [comment]
![Screenshot_20231113_133422_Nobis-fi](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/34696169/5d76dd21-1a54-4d67-b9a2-7bd8bbc643ab)
1 is the rear (second) sensor temerature
2.. it s the first.... I can choise 2 setting ... to use the external thermostat (now I use it) or use the sensor temeprature in the stove remote control wich i don't know 'casuse if i active it the temperatrue in the display is 99°.....always....I'll write to nobis fire service....

**Comment by vincentwolsink** [comment]
Is there also a temperature setting for the rear vent? Can you maybe also post a screenshot of the "Regolazioni" tab?

**Comment by merlino1975** [comment]
Is that? 
![Screenshot_20231113_213550_Nobis-fi](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/34696169/63d54f60-46dc-4c3b-b2b3-02a445b60463)

**Comment by vincentwolsink** [comment]
Please try [v0.2.9-beta3](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/releases/tag/v0.2.9-beta3)

**Comment by merlino1975** [comment]
how i can try? i must update?...or...? 

I'm sorry I'm a beginner

**Comment by merlino1975** [comment]
very strange, because, for now I have only looked at the functions and have not tried them, but with the new beta release I see the temperature of the temperature probe of the second ducting and the temperature of its target

**Comment by vincentwolsink** [comment]
@merlino1975 Are things working for you now?

An external thermostat will only override the main temperature control, not of any ducts/canalizations. If you want to use the main temperature control in HA you have to switch to the stove's built-in thermostat.

**Comment by merlino1975** [comment]
I will try to be more precise in the description. I apologize for my poor English. The stove has the possibility of using 3 temperature sensors: 1) a sensor is present in the stove remote control 2) an external thermostat to which you can only give contact. Ton or T0ff (practically performs the task only as a switch for the stove: when the room temperature is lower than the set temperature then the stove has maximum power set, if the room temperature is higher than the one set then the stove has minimum power) 3) the temperature sensor for the secondary ducting in HA I would need the temperature sensor of the remote control but if you can't do it anyway. I should be able to create the routine using a temperature sensor from another device. For now I'm still testing, I'm trying to understand how to use the new entities, it's a bit difficult for me because I'm a beginner..

**Comment by vincentwolsink** [comment]
All the sensors you are talking about are currently implemented in the integration. But you need to select the correct temperature/thermostat for your stove to operate on in your stove’s app. If you do that Home Assistant will follow.

If you believe you are missing something, please make a screenshot of the corresponding control/sensor in your stove’s app.

**Comment by merlino1975** [comment]
Well...when term ext is attivate then in app
![Screenshot_20231117_002245_Nobis-fi](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/34696169/dfa8c361-1f6d-4ce7-8d9c-b1986d542529)
When sensor remote control are attive the in app
![Screenshot_20231117_002338_WhatsApp](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/34696169/fab79219-25e1-40d3-a4ee-e3e7e76136e6)

**Comment by vincentwolsink** [comment]
Both are implemented. But you need to reload the integration after switching thermostat mode in the stove app.

<img width="317" alt="Scherm­afbeelding 2023-11-17 om 10 38 19" src="https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/1639734/c808cd6b-2a94-4287-ac61-17aeef7a9a0b">
<img width="349" alt="Scherm­afbeelding 2023-11-17 om 10 38 38" src="https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/1639734/57ab826d-2b71-4130-9bec-eac38ff70f94">

**Comment by merlino1975** [comment]
I must update?

**Comment by merlino1975** [comment]
okey..now I see 13 entities....and is all okey..but...I don't undestand.. I wold like to schedule the power of pellet about a determinate temperature in envyroment..but when I search device stufa.Salotto..I see wood parameters...but i wuold like to see pellet parameters...
he is a problem of my configuration or can you correct? in attach the pic.
![Screenshot 2023-11-21 21 48 12](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/34696169/0997a9a7-2f14-4c0e-a827-1608266ceade)

**Comment by merlino1975** [comment]
in reality it is possible that it will have to program both types of fuel

**Comment by vincentwolsink** [comment]
The climate entity adjusts to the mode the stove currently is in. For a hybrid stove the individual stove and pellet power controls are also available as separate entities.

**Comment by merlino1975** [comment]
Okey...and I would like understand...what the entità of the power of pellet or wood...? Because I see only fan speed...but power and fan speed are tuo separate entity...you can have power four and fan speed two...for example...well..or i can use a Mode called "auto" wich set power and fan speed for to reach fast and in economy the scheduled temperature

**Comment by merlino1975** [comment]
So I can use that...
![Screenshot_20231121_232952_Chrome](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/34696169/e2b1afdc-ad5a-42b9-a813-d3f868738e4f)

And Or that
![Screenshot_20231121_233041_Chrome](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/34696169/cca28955-e4ef-4d39-b170-f8dd8632606c)

**Comment by jipem01** [comment]
![Screenshot_20231121-233717_Home Assistant](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/assets/46441154/ef166a8e-1ba8-42c1-a93e-f3dceb28a443)

For hybrid stove you have access to Wood power and Pellet power entities. It's number entities, not climate attributes.

**Comment by merlino1975** [comment]
okey!!!!
